/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA {
  tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw Sup;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__P9czev7PkJcfQ9beI09c30g2Q)(void* p, NI op);
extern TNimType NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_;
N_LIB_PRIVATE TNimType NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_;
N_LIB_PRIVATE TNimType NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_;
static N_NIMCALL(void, Marker_tyRef__P9czev7PkJcfQ9beI09c30g2Q)(void* p, NI op) {
	tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* a;
	a = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
N_LIB_PRIVATE N_NIMCALL(void, puppy_commonDatInit000)(void) {
static TNimNode TM__KkSJCTbb1Qu87AydPmU9bog_0[1];
NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_.size = sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA);
NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_.align = NIM_ALIGNOF(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA);
NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_.kind = 17;
NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_.base = (&NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_);
TM__KkSJCTbb1Qu87AydPmU9bog_0[0].len = 0; TM__KkSJCTbb1Qu87AydPmU9bog_0[0].kind = 2;
NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_.node = &TM__KkSJCTbb1Qu87AydPmU9bog_0[0];
NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_.size = sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*);
NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_.align = NIM_ALIGNOF(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*);
NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_.kind = 22;
NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_.base = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_.marker = Marker_tyRef__P9czev7PkJcfQ9beI09c30g2Q;
}

