/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* fragment;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* paths;
tySequence__4eQHGndY6XBYpFOH09apV8Q* query;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__c0EiIY9aN7Vc09cjtTz7R9alA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, nsuRFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NU8, fromHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_109)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NI, parseHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_113)(NimStringDesc* s, NU8* number, NI start, NI maxLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr);
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y);
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_867)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__pureZunicode_842)(NI a, NI b);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_3217)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__stdZenumutils_80)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, parseSearch_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_198)(NimStringDesc* search);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr_system_7770)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringDesc* s, NimStringDesc* sub, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_pureZstrutils_1692)(NimStringDesc* s, NimStringDesc* sub);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_94)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHex_pureZstrutils_1853)(NI x, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE TNimType NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_;
N_LIB_PRIVATE TNimType NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_;
N_LIB_PRIVATE TNimType NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_;
N_LIB_PRIVATE TNimType NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_;
extern TNimType NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_16, "invalid hex integer: ", 21);
static NIM_CONST tyTuple__UV3llMMYFckfui8YMBuUZA TM__f9cSTabZSHQpqWgANarFrtw_36 = {((NimStringDesc*) NIM_NIL),
((NimStringDesc*) NIM_NIL)}
;
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_39, "://", 3);
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_54, "&", 1);
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_55, "=", 1);
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_57, "iterators.nim(258, 11) `len(a) == L` the length of the string changed while iterating over it", 93);
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_59, "iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__f9cSTabZSHQpqWgANarFrtw_61, "iterators.nim(173, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch_system_5258;
static N_NIMCALL(void, Marker_tySequence__4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q* a;
	NI T1_;
	a = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__c0EiIY9aN7Vc09cjtTz7R9alA)(void* p, NI op) {
	tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* a;
	a = (tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*)p;
	nimGCvisit((void*)(*a).scheme, op);
	nimGCvisit((void*)(*a).username, op);
	nimGCvisit((void*)(*a).password, op);
	nimGCvisit((void*)(*a).hostname, op);
	nimGCvisit((void*)(*a).port, op);
	nimGCvisit((void*)(*a).fragment, op);
	nimGCvisit((void*)(*a).paths, op);
	nimGCvisit((void*)(*a).query, op);
}
N_LIB_PRIVATE N_NIMCALL(NI, parseHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_113)(NimStringDesc* s, NU8* number, NI start, NI maxLen) {
	NI result;
	NI i;
	NU8 output;
	NIM_BOOL foundDigit;
	NI last;
	NI T1_;
	result = (NI)0;
	i = start;
	output = ((NU8) 0);
	foundDigit = NIM_FALSE;
	T1_ = (NI)0;
	{
		if (!(maxLen == ((NI) 0))) goto LA4_;
		T1_ = (s ? s->Sup.len : 0);
	}
	goto LA2_;
	LA4_: ;
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_4;
		if (nimAddInt(i, maxLen, &TM__f9cSTabZSHQpqWgANarFrtw_4)) { raiseOverflow(); };
		T1_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_4);
	}
	LA2_: ;
	last = (((s ? s->Sup.len : 0) <= T1_) ? (s ? s->Sup.len : 0) : T1_);
	{
		NIM_BOOL T9_;
		NIM_BOOL T10_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_5;
		NI TM__f9cSTabZSHQpqWgANarFrtw_6;
		NI TM__f9cSTabZSHQpqWgANarFrtw_7;
		T9_ = (NIM_BOOL)0;
		T10_ = (NIM_BOOL)0;
		if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_5)) { raiseOverflow(); };
		T10_ = ((NI)(TM__f9cSTabZSHQpqWgANarFrtw_5) < last);
		if (!(T10_)) goto LA11_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T10_ = ((NU8)(s->data[i]) == (NU8)(48));
		LA11_: ;
		T9_ = T10_;
		if (!(T9_)) goto LA12_;
		if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_6)) { raiseOverflow(); };
		if ((NU)((NI)(TM__f9cSTabZSHQpqWgANarFrtw_6)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__f9cSTabZSHQpqWgANarFrtw_6),(s ? s->Sup.len : 0)-1); }
		T9_ = (((NU8)(s->data[(NI)(TM__f9cSTabZSHQpqWgANarFrtw_6)])) == ((NU8)(120)) || ((NU8)(s->data[(NI)(TM__f9cSTabZSHQpqWgANarFrtw_6)])) == ((NU8)(88)));
		LA12_: ;
		if (!T9_) goto LA13_;
		if (nimAddInt(i, ((NI) 2), &TM__f9cSTabZSHQpqWgANarFrtw_7)) { raiseOverflow(); };
		i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_7);
	}
	goto LA7_;
	LA13_: ;
	{
		NIM_BOOL T16_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_8;
		T16_ = (NIM_BOOL)0;
		T16_ = (i < last);
		if (!(T16_)) goto LA17_;
		if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
		T16_ = ((NU8)(s->data[i]) == (NU8)(35));
		LA17_: ;
		if (!T16_) goto LA18_;
		if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_8)) { raiseOverflow(); };
		i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_8);
	}
	goto LA7_;
	LA18_: ;
	LA7_: ;
	{
		while (1) {
			NI TM__f9cSTabZSHQpqWgANarFrtw_14;
			if (!(i < last)) goto LA21;
			if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
			switch (((NU8)(s->data[i]))) {
			case 95:
			{
			}
			break;
			case 48 ... 57:
			{
				NI TM__f9cSTabZSHQpqWgANarFrtw_9;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 48), &TM__f9cSTabZSHQpqWgANarFrtw_9)) { raiseOverflow(); };
				output = (NU8)((NU8)((NU32)(output) << (NU32)(((NI) 4))) | ((NU8) ((NI)(TM__f9cSTabZSHQpqWgANarFrtw_9))));
				foundDigit = NIM_TRUE;
			}
			break;
			case 97 ... 102:
			{
				NI TM__f9cSTabZSHQpqWgANarFrtw_10;
				NI TM__f9cSTabZSHQpqWgANarFrtw_11;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 97), &TM__f9cSTabZSHQpqWgANarFrtw_10)) { raiseOverflow(); };
				if (nimAddInt((NI)(TM__f9cSTabZSHQpqWgANarFrtw_10), ((NI) 10), &TM__f9cSTabZSHQpqWgANarFrtw_11)) { raiseOverflow(); };
				output = (NU8)((NU8)((NU32)(output) << (NU32)(((NI) 4))) | ((NU8) ((NI)(TM__f9cSTabZSHQpqWgANarFrtw_11))));
				foundDigit = NIM_TRUE;
			}
			break;
			case 65 ... 70:
			{
				NI TM__f9cSTabZSHQpqWgANarFrtw_12;
				NI TM__f9cSTabZSHQpqWgANarFrtw_13;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				if (nimSubInt(((NU8)(s->data[i])), ((NI) 65), &TM__f9cSTabZSHQpqWgANarFrtw_12)) { raiseOverflow(); };
				if (nimAddInt((NI)(TM__f9cSTabZSHQpqWgANarFrtw_12), ((NI) 10), &TM__f9cSTabZSHQpqWgANarFrtw_13)) { raiseOverflow(); };
				output = (NU8)((NU8)((NU32)(output) << (NU32)(((NI) 4))) | ((NU8) ((NI)(TM__f9cSTabZSHQpqWgANarFrtw_13))));
				foundDigit = NIM_TRUE;
			}
			break;
			default:
			{
				goto LA20;
			}
			break;
			}
			if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_14)) { raiseOverflow(); };
			i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_14);
		} LA21: ;
	} LA20: ;
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_15;
		if (!foundDigit) goto LA29_;
		(*number) = output;
		if (nimSubInt(i, start, &TM__f9cSTabZSHQpqWgANarFrtw_15)) { raiseOverflow(); };
		result = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_15);
	}
	LA29_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem_system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem_system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent__system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent__system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_system_5305((&gch_system_5258.zct), c);
}
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent__system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent__system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT_system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_system_5311(src);
		incRef_system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_system_5311((*dest));
		decRef_system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(NU8, fromHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_109)(NimStringDesc* s) {
	NU8 result;
	NI p;
	result = (NU8)0;
	p = parseHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_113(s, (&result), ((NI) 0), ((NI) 0));
	{
		NIM_BOOL T3_;
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((p == (s ? s->Sup.len : 0)));
		if (T3_) goto LA4_;
		T3_ = (p == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
		T7_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_ = (NimStringDesc*)0;
		T8_ = rawNewString((s ? s->Sup.len : 0) + 21);
appendString(T8_, ((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_16));
appendString(T8_, s);
		asgnRef((void**) (&(*T7_).Sup.Sup.message), T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "fromHex", "strutils.nim", 1046);
	}
	LA5_: ;
	return result;
}
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_867)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM__f9cSTabZSHQpqWgANarFrtw_17;
	NI TM__f9cSTabZSHQpqWgANarFrtw_18;
	result = (NimStringDesc*)0;
	a = x.a;
	if (nimSubInt(x.b, a, &TM__f9cSTabZSHQpqWgANarFrtw_17)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__f9cSTabZSHQpqWgANarFrtw_17), ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_18)) { raiseOverflow(); };
	L = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_18);
	if ((L) < ((NI) 0) || (L) > ((NI) 2147483647)){ raiseRangeErrorI(L, ((NI) 0), ((NI) 2147483647)); }
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__f9cSTabZSHQpqWgANarFrtw_19;
				NI TM__f9cSTabZSHQpqWgANarFrtw_20;
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				if ((NU)(i) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (nimAddInt(i, a, &TM__f9cSTabZSHQpqWgANarFrtw_19)) { raiseOverflow(); };
				if ((NU)((NI)(TM__f9cSTabZSHQpqWgANarFrtw_19)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__f9cSTabZSHQpqWgANarFrtw_19),(s ? s->Sup.len : 0)-1); }
				result->data[i] = s->data[(NI)(TM__f9cSTabZSHQpqWgANarFrtw_19)];
				if (nimAddInt(i_2, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_20)) { raiseOverflow(); };
				i_2 = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_20);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__pureZunicode_842)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105)(NimStringDesc* s) {
	NimStringDesc* result;
	NI i;
	result = (NimStringDesc*)0;
	if (((s ? s->Sup.len : 0)) < ((NI) 0) || ((s ? s->Sup.len : 0)) > ((NI) 2147483647)){ raiseRangeErrorI((s ? s->Sup.len : 0), ((NI) 0), ((NI) 2147483647)); }
	result = rawNewString(((NI) ((s ? s->Sup.len : 0))));
	i = ((NI) 0);
	{
		while (1) {
			NI TM__f9cSTabZSHQpqWgANarFrtw_24;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
			switch (((NU8)(s->data[i]))) {
			case 37:
			{
				NI TM__f9cSTabZSHQpqWgANarFrtw_21;
				NI TM__f9cSTabZSHQpqWgANarFrtw_22;
				tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T4_;
				NimStringDesc* T5_;
				NU8 T6_;
				NI TM__f9cSTabZSHQpqWgANarFrtw_23;
				if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_21)) { raiseOverflow(); };
				if (nimAddInt(i, ((NI) 2), &TM__f9cSTabZSHQpqWgANarFrtw_22)) { raiseOverflow(); };
				T4_ = dotdot__pureZunicode_842((NI)(TM__f9cSTabZSHQpqWgANarFrtw_21), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_22));
				T5_ = (NimStringDesc*)0;
				T5_ = X5BX5D__pureZunicode_867(s, T4_);
				T6_ = (NU8)0;
				T6_ = fromHex_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_109(T5_);
				result = addChar(result, ((NIM_CHAR) (((NI) (T6_)))));
				if (nimAddInt(i, ((NI) 2), &TM__f9cSTabZSHQpqWgANarFrtw_23)) { raiseOverflow(); };
				i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_23);
			}
			break;
			case 43:
			{
				result = addChar(result, 32);
			}
			break;
			default:
			{
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				result = addChar(result, s->data[i]);
			}
			break;
			}
			if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_24)) { raiseOverflow(); };
			i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_24);
		} LA2: ;
	}
	return result;
}
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_3217)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM__f9cSTabZSHQpqWgANarFrtw_25;
	NI TM__f9cSTabZSHQpqWgANarFrtw_26;
	NI TM__f9cSTabZSHQpqWgANarFrtw_27;
	result = (NimStringDesc*)0;
	a = x.a;
	if (nimSubInt((s ? s->Sup.len : 0), x.b, &TM__f9cSTabZSHQpqWgANarFrtw_25)) { raiseOverflow(); };
	if (nimSubInt((NI)(TM__f9cSTabZSHQpqWgANarFrtw_25), a, &TM__f9cSTabZSHQpqWgANarFrtw_26)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__f9cSTabZSHQpqWgANarFrtw_26), ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_27)) { raiseOverflow(); };
	L = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_27);
	if ((L) < ((NI) 0) || (L) > ((NI) 2147483647)){ raiseRangeErrorI(L, ((NI) 0), ((NI) 2147483647)); }
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__f9cSTabZSHQpqWgANarFrtw_28;
				NI TM__f9cSTabZSHQpqWgANarFrtw_29;
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				if ((NU)(i) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (nimAddInt(i, a, &TM__f9cSTabZSHQpqWgANarFrtw_28)) { raiseOverflow(); };
				if ((NU)((NI)(TM__f9cSTabZSHQpqWgANarFrtw_28)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__f9cSTabZSHQpqWgANarFrtw_28),(s ? s->Sup.len : 0)-1); }
				result->data[i] = s->data[(NI)(TM__f9cSTabZSHQpqWgANarFrtw_28)];
				if (nimAddInt(i_2, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_29)) { raiseOverflow(); };
				i_2 = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_29);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__stdZenumutils_80)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_system_5311(p);
	decRef_system_5356(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tySequence__4eQHGndY6XBYpFOH09apV8Q*, parseSearch_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_198)(NimStringDesc* search) {
	tySequence__4eQHGndY6XBYpFOH09apV8Q* result;
	result = (tySequence__4eQHGndY6XBYpFOH09apV8Q*)0;
	{
		NimStringDesc* pairStr;
		NI lastX60gensym34_;
		NI splitsX60gensym34_;
		pairStr = (NimStringDesc*)0;
		lastX60gensym34_ = ((NI) 0);
		splitsX60gensym34_ = ((NI) -1);
		{
			while (1) {
				NI firstX60gensym34_;
				NI TM__f9cSTabZSHQpqWgANarFrtw_35;
				tySequence__sM4lkSb7zS6F7OVMvW9cffQ* pair;
				tyTuple__UV3llMMYFckfui8YMBuUZA kv;
				NI T22_;
				NimStringDesc* T23_;
				NimStringDesc* T24_;
				NI TM__f9cSTabZSHQpqWgANarFrtw_37;
				NI TM__f9cSTabZSHQpqWgANarFrtw_38;
				if (!(lastX60gensym34_ <= (search ? search->Sup.len : 0))) goto LA3;
				firstX60gensym34_ = lastX60gensym34_;
				{
					while (1) {
						NIM_BOOL T6_;
						NI TM__f9cSTabZSHQpqWgANarFrtw_34;
						T6_ = (NIM_BOOL)0;
						T6_ = (lastX60gensym34_ < (search ? search->Sup.len : 0));
						if (!(T6_)) goto LA7_;
						if ((NU)(lastX60gensym34_) >= (NU)(search ? search->Sup.len : 0)){ raiseIndexError2(lastX60gensym34_,(search ? search->Sup.len : 0)-1); }
						T6_ = !(((NU8)(search->data[lastX60gensym34_]) == (NU8)(38)));
						LA7_: ;
						if (!T6_) goto LA5;
						if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_34)) { raiseOverflow(); };
						lastX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_34);
					} LA5: ;
				}
				{
					if (!(splitsX60gensym34_ == ((NI) 0))) goto LA10_;
					lastX60gensym34_ = (search ? search->Sup.len : 0);
				}
				LA10_: ;
				if (nimSubInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_35)) { raiseOverflow(); };
				pairStr = substr_system_7770(search, firstX60gensym34_, (NI)(TM__f9cSTabZSHQpqWgANarFrtw_35));
				pair = nsuSplitChar(pairStr, 61, ((NI) 1));
				nimZeroMem((void*)(&kv), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
				{
					NI T14_;
					T14_ = (pair ? pair->Sup.len : 0);
					if (!(T14_ == ((NI) 2))) goto LA15_;
					if ((NU)(((NI) 0)) >= (NU)(pair ? pair->Sup.len : 0)){ raiseIndexError2(((NI) 0),(pair ? pair->Sup.len : 0)-1); }
					kv.Field0 = decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105(pair->data[((NI) 0)]);
					if ((NU)(((NI) 1)) >= (NU)(pair ? pair->Sup.len : 0)){ raiseIndexError2(((NI) 1),(pair ? pair->Sup.len : 0)-1); }
					kv.Field1 = decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105(pair->data[((NI) 1)]);
				}
				goto LA12_;
				LA15_: ;
				{
					NI T18_;
					T18_ = (pair ? pair->Sup.len : 0);
					if (!(T18_ == ((NI) 1))) goto LA19_;
					if ((NU)(((NI) 0)) >= (NU)(pair ? pair->Sup.len : 0)){ raiseIndexError2(((NI) 0),(pair ? pair->Sup.len : 0)-1); }
					kv.Field0 = decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105(pair->data[((NI) 0)]);
					kv.Field1 = ((NimStringDesc*) NIM_NIL);
				}
				goto LA12_;
				LA19_: ;
				{
					kv.Field0 = copyString(TM__f9cSTabZSHQpqWgANarFrtw_36.Field0);
					kv.Field1 = copyString(TM__f9cSTabZSHQpqWgANarFrtw_36.Field1);
				}
				LA12_: ;
				result = (tySequence__4eQHGndY6XBYpFOH09apV8Q*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_));
				T22_ = result->Sup.len++;
				T23_ = (NimStringDesc*)0;
				T23_ = result->data[T22_].Field0; result->data[T22_].Field0 = copyStringRC1(kv.Field0);
				if (T23_) nimGCunrefNoCycle(T23_);
				T24_ = (NimStringDesc*)0;
				T24_ = result->data[T22_].Field1; result->data[T22_].Field1 = copyStringRC1(kv.Field1);
				if (T24_) nimGCunrefNoCycle(T24_);
				{
					if (!(splitsX60gensym34_ == ((NI) 0))) goto LA27_;
					goto LA2;
				}
				LA27_: ;
				if (nimSubInt(splitsX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_37)) { raiseOverflow(); };
				splitsX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_37);
				if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_38)) { raiseOverflow(); };
				lastX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_38);
			} LA3: ;
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*, parseUrl_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_214)(NimStringDesc* s) {
	tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* result;
	NimStringDesc* s_2;
	tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url;
	tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* T1_;
	NI hasFragment;
	NI hasSearch;
	NI hasScheme;
	NI hasLogin;
	NI hasPath;
	NI hasPort;
	NimStringDesc* T73_;
{	result = (tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*)0;
	s_2 = copyString(s);
	T1_ = (tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*)0;
	T1_ = (tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*) newObj((&NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_), sizeof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg));
	url = T1_;
	hasFragment = nsuRFindChar(s_2, 35, ((NI) 0), ((NI) -1));
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_30;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T6_;
		NimStringDesc* T7_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_31;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T8_;
		if (!!((hasFragment == ((NI) -1)))) goto LA4_;
		if (nimAddInt(hasFragment, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_30)) { raiseOverflow(); };
		T6_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_30), ((NI) 1));
		T7_ = (NimStringDesc*)0;
		T7_ = X5BX5D__pureZunicode_3217(s_2, T6_);
		asgnRef((void**) (&(*url).fragment), decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105(T7_));
		if (nimSubInt(hasFragment, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_31)) { raiseOverflow(); };
		T8_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_31));
		s_2 = X5BX5D__pureZunicode_867(s_2, T8_);
	}
	LA4_: ;
	hasSearch = nsuRFindChar(s_2, 63, ((NI) 0), ((NI) -1));
	{
		NimStringDesc* search;
		NI TM__f9cSTabZSHQpqWgANarFrtw_32;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T13_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_33;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T14_;
		if (!!((hasSearch == ((NI) -1)))) goto LA11_;
		if (nimAddInt(hasSearch, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_32)) { raiseOverflow(); };
		T13_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_32), ((NI) 1));
		search = X5BX5D__pureZunicode_3217(s_2, T13_);
		if (nimSubInt(hasSearch, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_33)) { raiseOverflow(); };
		T14_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_33));
		s_2 = X5BX5D__pureZunicode_867(s_2, T14_);
		asgnRef((void**) (&(*url).query), parseSearch_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_198(search));
	}
	LA11_: ;
	hasScheme = nsuFindStr(s_2, ((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_39), ((NI) 0), ((NI) 0));
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_40;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T19_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_41;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T20_;
		if (!!((hasScheme == ((NI) -1)))) goto LA17_;
		if (nimSubInt(hasScheme, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_40)) { raiseOverflow(); };
		T19_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_40));
		asgnRef((void**) (&(*url).scheme), X5BX5D__pureZunicode_867(s_2, T19_));
		if (nimAddInt(hasScheme, ((NI) 3), &TM__f9cSTabZSHQpqWgANarFrtw_41)) { raiseOverflow(); };
		T20_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_41), ((NI) 1));
		s_2 = X5BX5D__pureZunicode_3217(s_2, T20_);
	}
	LA17_: ;
	hasLogin = nsuFindChar(s_2, 64, ((NI) 0), ((NI) 0));
	{
		NimStringDesc* login;
		NI TM__f9cSTabZSHQpqWgANarFrtw_42;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T25_;
		NI hasPassword;
		NI TM__f9cSTabZSHQpqWgANarFrtw_45;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T34_;
		if (!!((hasLogin == ((NI) -1)))) goto LA23_;
		if (nimSubInt(hasLogin, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_42)) { raiseOverflow(); };
		T25_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_42));
		login = X5BX5D__pureZunicode_867(s_2, T25_);
		hasPassword = nsuFindChar(login, 58, ((NI) 0), ((NI) 0));
		{
			NI TM__f9cSTabZSHQpqWgANarFrtw_43;
			tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T30_;
			NI TM__f9cSTabZSHQpqWgANarFrtw_44;
			tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T31_;
			if (!!((hasPassword == ((NI) -1)))) goto LA28_;
			if (nimSubInt(hasPassword, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_43)) { raiseOverflow(); };
			T30_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_43));
			asgnRef((void**) (&(*url).username), X5BX5D__pureZunicode_867(login, T30_));
			if (nimAddInt(hasPassword, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_44)) { raiseOverflow(); };
			T31_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_44), ((NI) 1));
			asgnRef((void**) (&(*url).password), X5BX5D__pureZunicode_3217(login, T31_));
		}
		goto LA26_;
		LA28_: ;
		{
			NimStringDesc* T33_;
			T33_ = (NimStringDesc*)0;
			T33_ = (*url).username; (*url).username = copyStringRC1(login);
			if (T33_) nimGCunrefNoCycle(T33_);
		}
		LA26_: ;
		if (nimAddInt(hasLogin, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_45)) { raiseOverflow(); };
		T34_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_45), ((NI) 1));
		s_2 = X5BX5D__pureZunicode_3217(s_2, T34_);
	}
	LA23_: ;
	hasPath = nsuFindChar(s_2, 47, ((NI) 0), ((NI) 0));
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_51;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T58_;
		if (!!((hasPath == ((NI) -1)))) goto LA37_;
		{
			NimStringDesc* part;
			NimStringDesc* colontmp_;
			NI TM__f9cSTabZSHQpqWgANarFrtw_46;
			tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T40_;
			NI lastX60gensym34_;
			NI splitsX60gensym34_;
			part = (NimStringDesc*)0;
			colontmp_ = (NimStringDesc*)0;
			if (nimAddInt(hasPath, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_46)) { raiseOverflow(); };
			T40_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_46), ((NI) 1));
			colontmp_ = X5BX5D__pureZunicode_3217(s_2, T40_);
			lastX60gensym34_ = ((NI) 0);
			splitsX60gensym34_ = ((NI) -1);
			{
				while (1) {
					NI firstX60gensym34_;
					NI TM__f9cSTabZSHQpqWgANarFrtw_48;
					NimStringDesc* T51_;
					NI T52_;
					NimStringDesc* T53_;
					NI TM__f9cSTabZSHQpqWgANarFrtw_49;
					NI TM__f9cSTabZSHQpqWgANarFrtw_50;
					if (!(lastX60gensym34_ <= (colontmp_ ? colontmp_->Sup.len : 0))) goto LA42;
					firstX60gensym34_ = lastX60gensym34_;
					{
						while (1) {
							NIM_BOOL T45_;
							NI TM__f9cSTabZSHQpqWgANarFrtw_47;
							T45_ = (NIM_BOOL)0;
							T45_ = (lastX60gensym34_ < (colontmp_ ? colontmp_->Sup.len : 0));
							if (!(T45_)) goto LA46_;
							if ((NU)(lastX60gensym34_) >= (NU)(colontmp_ ? colontmp_->Sup.len : 0)){ raiseIndexError2(lastX60gensym34_,(colontmp_ ? colontmp_->Sup.len : 0)-1); }
							T45_ = !(((NU8)(colontmp_->data[lastX60gensym34_]) == (NU8)(47)));
							LA46_: ;
							if (!T45_) goto LA44;
							if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_47)) { raiseOverflow(); };
							lastX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_47);
						} LA44: ;
					}
					{
						if (!(splitsX60gensym34_ == ((NI) 0))) goto LA49_;
						lastX60gensym34_ = (colontmp_ ? colontmp_->Sup.len : 0);
					}
					LA49_: ;
					if (nimSubInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_48)) { raiseOverflow(); };
					part = substr_system_7770(colontmp_, firstX60gensym34_, (NI)(TM__f9cSTabZSHQpqWgANarFrtw_48));
					T51_ = (NimStringDesc*)0;
					T51_ = decodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_105(part);
					asgnRef((void**) (&(*url).paths), (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3((TGenericSeq*)((*url).paths), (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_)));
					T52_ = (*url).paths->Sup.len++;
					T53_ = (NimStringDesc*)0;
					T53_ = (*url).paths->data[T52_]; (*url).paths->data[T52_] = copyStringRC1(T51_);
					if (T53_) nimGCunrefNoCycle(T53_);
					{
						if (!(splitsX60gensym34_ == ((NI) 0))) goto LA56_;
						goto LA41;
					}
					LA56_: ;
					if (nimSubInt(splitsX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_49)) { raiseOverflow(); };
					splitsX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_49);
					if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_50)) { raiseOverflow(); };
					lastX60gensym34_ = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_50);
				} LA42: ;
			} LA41: ;
		}
		if (nimSubInt(hasPath, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_51)) { raiseOverflow(); };
		T58_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_51));
		s_2 = X5BX5D__pureZunicode_867(s_2, T58_);
	}
	LA37_: ;
	hasPort = nsuFindChar(s_2, 58, ((NI) 0), ((NI) 0));
	{
		NI TM__f9cSTabZSHQpqWgANarFrtw_52;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T63_;
		NI TM__f9cSTabZSHQpqWgANarFrtw_53;
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T64_;
		if (!!((hasPort == ((NI) -1)))) goto LA61_;
		if (nimAddInt(hasPort, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_52)) { raiseOverflow(); };
		T63_ = dotdot__stdZenumutils_80((NI)(TM__f9cSTabZSHQpqWgANarFrtw_52), ((NI) 1));
		asgnRef((void**) (&(*url).port), X5BX5D__pureZunicode_3217(s_2, T63_));
		if (nimSubInt(hasPort, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_53)) { raiseOverflow(); };
		T64_ = dotdot__pureZunicode_842(((NI) 0), (NI)(TM__f9cSTabZSHQpqWgANarFrtw_53));
		s_2 = X5BX5D__pureZunicode_867(s_2, T64_);
	}
	LA61_: ;
	{
		NIM_BOOL T67_;
		NIM_BOOL T68_;
		T67_ = (NIM_BOOL)0;
		T68_ = (NIM_BOOL)0;
		T68_ = (hasSearch == ((NI) -1));
		if (!(T68_)) goto LA69_;
		T68_ = contains_pureZstrutils_1692(s_2, ((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_54));
		LA69_: ;
		T67_ = T68_;
		if (T67_) goto LA70_;
		T67_ = contains_pureZstrutils_1692(s_2, ((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_55));
		LA70_: ;
		if (!T67_) goto LA71_;
		asgnRef((void**) (&(*url).query), parseSearch_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_198(s_2));
		s_2 = ((NimStringDesc*) NIM_NIL);
	}
	LA71_: ;
	T73_ = (NimStringDesc*)0;
	T73_ = (*url).hostname; (*url).hostname = copyStringRC1(s_2);
	if (T73_) nimGCunrefNoCycle(T73_);
	result = url;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_94)(NimStringDesc* s) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	if (((s ? s->Sup.len : 0)) < ((NI) 0) || ((s ? s->Sup.len : 0)) > ((NI) 2147483647)){ raiseRangeErrorI((s ? s->Sup.len : 0), ((NI) 0), ((NI) 2147483647)); }
	result = rawNewString(((NI) ((s ? s->Sup.len : 0))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI) 0);
		L = (s ? s->Sup.len : 0);
		{
			while (1) {
				NI TM__f9cSTabZSHQpqWgANarFrtw_56;
				if (!(i < L)) goto LA3;
				if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				c = s->data[i];
				switch (((NU8)(c))) {
				case 32:
				{
					result = addChar(result, 43);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 48 ... 57:
				case 45:
				case 46:
				case 95:
				case 126:
				{
					result = addChar(result, c);
				}
				break;
				default:
				{
					NimStringDesc* T7_;
					result = addChar(result, 37);
					T7_ = (NimStringDesc*)0;
					T7_ = toHex_pureZstrutils_1853(((NU8)(c)), ((NI) 2));
					result = resizeString(result, (T7_ ? T7_->Sup.len : 0) + 0);
appendString(result, T7_);
				}
				break;
				}
				if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_56)) { raiseOverflow(); };
				i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_56);
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA10_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_57));
				}
				LA10_: ;
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, path_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_542)(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		NI T3_;
		T3_ = ((*url).paths ? (*url).paths->Sup.len : 0);
		if (!(((NI) 0) < T3_)) goto LA4_;
		{
			NimStringDesc** part;
			NI i;
			NI L;
			NI T7_;
			part = (NimStringDesc**)0;
			i = ((NI) 0);
			T7_ = ((*url).paths ? (*url).paths->Sup.len : 0);
			L = T7_;
			{
				while (1) {
					NimStringDesc* T10_;
					NI TM__f9cSTabZSHQpqWgANarFrtw_58;
					if (!(i < L)) goto LA9;
					if ((NU)(i) >= (NU)((*url).paths ? (*url).paths->Sup.len : 0)){ raiseIndexError2(i,((*url).paths ? (*url).paths->Sup.len : 0)-1); }
					part = (&(*url).paths->data[i]);
					result = addChar(result, 47);
					T10_ = (NimStringDesc*)0;
					T10_ = encodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_94((*part));
					result = resizeString(result, (T10_ ? T10_->Sup.len : 0) + 0);
appendString(result, T10_);
					if (nimAddInt(i, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_58)) { raiseOverflow(); };
					i = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_58);
					{
						NI T13_;
						T13_ = ((*url).paths ? (*url).paths->Sup.len : 0);
						if (!!((T13_ == L))) goto LA14_;
						failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_59));
					}
					LA14_: ;
				} LA9: ;
			}
		}
	}
	LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, search_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_506)(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		NI i;
		tyTuple__UV3llMMYFckfui8YMBuUZA pair;
		NI i_2;
		NI L;
		NI T2_;
		i = (NI)0;
		nimZeroMem((void*)(&pair), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
		i_2 = ((NI) 0);
		T2_ = ((*url).query ? (*url).query->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NimStringDesc* T9_;
				NimStringDesc* T10_;
				NI TM__f9cSTabZSHQpqWgANarFrtw_60;
				if (!(i_2 < L)) goto LA4;
				i = i_2;
				if ((NU)(i_2) >= (NU)((*url).query ? (*url).query->Sup.len : 0)){ raiseIndexError2(i_2,((*url).query ? (*url).query->Sup.len : 0)-1); }
				pair.Field0 = (*url).query->data[i_2].Field0;
				pair.Field1 = (*url).query->data[i_2].Field1;
				{
					if (!(((NI) 0) < i)) goto LA7_;
					result = addChar(result, 38);
				}
				LA7_: ;
				T9_ = (NimStringDesc*)0;
				T9_ = encodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_94(pair.Field0);
				result = resizeString(result, (T9_ ? T9_->Sup.len : 0) + 0);
appendString(result, T9_);
				result = addChar(result, 61);
				T10_ = (NimStringDesc*)0;
				T10_ = encodeUrlComponent_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_94(pair.Field1);
				result = resizeString(result, (T10_ ? T10_->Sup.len : 0) + 0);
appendString(result, T10_);
				if (nimAddInt(i_2, ((NI) 1), &TM__f9cSTabZSHQpqWgANarFrtw_60)) { raiseOverflow(); };
				i_2 = (NI)(TM__f9cSTabZSHQpqWgANarFrtw_60);
				{
					NI T13_;
					T13_ = ((*url).query ? (*url).query->Sup.len : 0);
					if (!!((T13_ == L))) goto LA14_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__f9cSTabZSHQpqWgANarFrtw_61));
				}
				LA14_: ;
			} LA4: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, urlly_urllyDatInit000)(void) {
static TNimNode* TM__f9cSTabZSHQpqWgANarFrtw_2_8[8];
static TNimNode* TM__f9cSTabZSHQpqWgANarFrtw_3_2[2];
static TNimNode TM__f9cSTabZSHQpqWgANarFrtw_0[12];
NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_.size = sizeof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg);
NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_.align = NIM_ALIGNOF(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg);
NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_.kind = 18;
NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_.base = 0;
TM__f9cSTabZSHQpqWgANarFrtw_2_8[0] = &TM__f9cSTabZSHQpqWgANarFrtw_0[1];
TM__f9cSTabZSHQpqWgANarFrtw_0[1].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[1].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, scheme);
TM__f9cSTabZSHQpqWgANarFrtw_0[1].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[1].name = "scheme";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[1] = &TM__f9cSTabZSHQpqWgANarFrtw_0[2];
TM__f9cSTabZSHQpqWgANarFrtw_0[2].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[2].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, username);
TM__f9cSTabZSHQpqWgANarFrtw_0[2].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[2].name = "username";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[2] = &TM__f9cSTabZSHQpqWgANarFrtw_0[3];
TM__f9cSTabZSHQpqWgANarFrtw_0[3].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[3].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, password);
TM__f9cSTabZSHQpqWgANarFrtw_0[3].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[3].name = "password";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[3] = &TM__f9cSTabZSHQpqWgANarFrtw_0[4];
TM__f9cSTabZSHQpqWgANarFrtw_0[4].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[4].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, hostname);
TM__f9cSTabZSHQpqWgANarFrtw_0[4].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[4].name = "hostname";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[4] = &TM__f9cSTabZSHQpqWgANarFrtw_0[5];
TM__f9cSTabZSHQpqWgANarFrtw_0[5].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[5].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, port);
TM__f9cSTabZSHQpqWgANarFrtw_0[5].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[5].name = "port";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[5] = &TM__f9cSTabZSHQpqWgANarFrtw_0[6];
TM__f9cSTabZSHQpqWgANarFrtw_0[6].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[6].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, fragment);
TM__f9cSTabZSHQpqWgANarFrtw_0[6].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[6].name = "fragment";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[6] = &TM__f9cSTabZSHQpqWgANarFrtw_0[7];
TM__f9cSTabZSHQpqWgANarFrtw_0[7].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[7].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, paths);
TM__f9cSTabZSHQpqWgANarFrtw_0[7].typ = (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_);
TM__f9cSTabZSHQpqWgANarFrtw_0[7].name = "paths";
TM__f9cSTabZSHQpqWgANarFrtw_2_8[7] = &TM__f9cSTabZSHQpqWgANarFrtw_0[8];
NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_.size = sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA);
NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_.align = NIM_ALIGNOF(tyTuple__UV3llMMYFckfui8YMBuUZA);
NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_.kind = 18;
NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_.base = 0;
TM__f9cSTabZSHQpqWgANarFrtw_3_2[0] = &TM__f9cSTabZSHQpqWgANarFrtw_0[10];
TM__f9cSTabZSHQpqWgANarFrtw_0[10].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[10].offset = offsetof(tyTuple__UV3llMMYFckfui8YMBuUZA, Field0);
TM__f9cSTabZSHQpqWgANarFrtw_0[10].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[10].name = "Field0";
TM__f9cSTabZSHQpqWgANarFrtw_3_2[1] = &TM__f9cSTabZSHQpqWgANarFrtw_0[11];
TM__f9cSTabZSHQpqWgANarFrtw_0[11].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[11].offset = offsetof(tyTuple__UV3llMMYFckfui8YMBuUZA, Field1);
TM__f9cSTabZSHQpqWgANarFrtw_0[11].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__f9cSTabZSHQpqWgANarFrtw_0[11].name = "Field1";
TM__f9cSTabZSHQpqWgANarFrtw_0[9].len = 2; TM__f9cSTabZSHQpqWgANarFrtw_0[9].kind = 2; TM__f9cSTabZSHQpqWgANarFrtw_0[9].sons = &TM__f9cSTabZSHQpqWgANarFrtw_3_2[0];
NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_.node = &TM__f9cSTabZSHQpqWgANarFrtw_0[9];
NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_.size = sizeof(tySequence__4eQHGndY6XBYpFOH09apV8Q*);
NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_.align = NIM_ALIGNOF(tySequence__4eQHGndY6XBYpFOH09apV8Q*);
NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_.kind = 24;
NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_.base = (&NTILstring_stringT__UV3llMMYFckfui8YMBuUZA_);
NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_.marker = Marker_tySequence__4eQHGndY6XBYpFOH09apV8Q;
TM__f9cSTabZSHQpqWgANarFrtw_0[8].kind = 1;
TM__f9cSTabZSHQpqWgANarFrtw_0[8].offset = offsetof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg, query);
TM__f9cSTabZSHQpqWgANarFrtw_0[8].typ = (&NTIseqLLstring_stringTT__4eQHGndY6XBYpFOH09apV8Q_);
TM__f9cSTabZSHQpqWgANarFrtw_0[8].name = "query";
TM__f9cSTabZSHQpqWgANarFrtw_0[0].len = 8; TM__f9cSTabZSHQpqWgANarFrtw_0[0].kind = 2; TM__f9cSTabZSHQpqWgANarFrtw_0[0].sons = &TM__f9cSTabZSHQpqWgANarFrtw_2_8[0];
NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_.node = &TM__f9cSTabZSHQpqWgANarFrtw_0[0];
NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_.size = sizeof(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*);
NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_.align = NIM_ALIGNOF(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*);
NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_.kind = 22;
NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_.base = (&NTIurl58objecttype__BLDUGAmrTNcm5NpX5hztCg_);
NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_.marker = Marker_tyRef__c0EiIY9aN7Vc09cjtTz7R9alA;
}

