/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA;
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
typedef NIM_CHAR tyArray__KzYsGdAcGnUxHpbjbCVtbQ[3];
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU32 tyArray__gEFnRB9aCNYsXpRJmdSsCKw[256];
typedef tyArray__gEFnRB9aCNYsXpRJmdSsCKw tyArray__TLfYrv9bhDLPrkLaYgjq2Ow[8];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_284)(NIM_CHAR* x, NI xLen_0, NIM_CHAR* y, NI yLen_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_867)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__pureZunicode_842)(NI a, NI b);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_165)(NimStringDesc** dst, NimStringDesc* src, tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA dataFormat);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NI, nextZeroByte_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_198)(NimStringDesc* s, NI start);
static N_INLINE(NU32, read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187)(NimStringDesc* s, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, inflate_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZinflate_478)(NimStringDesc** dst, NimStringDesc* src, NI pos);
static N_INLINE(NU32, crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_34)(NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(NU32, crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_38)(NU32 v, NimStringDesc* data);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_CHAR, X5BX5D__system_7355)(NimStringDesc* s, NI i);
N_LIB_PRIVATE N_NIMCALL(NU32, adler32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcommon_584)(NimStringDesc* data);
static NIM_CONST tyArray__KzYsGdAcGnUxHpbjbCVtbQ TM__UqbkX1qqvV1mfEv19avhonw_7 = {31,
139,
8}
;
extern TNimType NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_;
extern TNimType NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_;
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_8, "Invalid buffer, unable to uncompress", 36);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_9, "Failed gzip identification values check", 39);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_10, "Unsupported compression method", 30);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_11, "Reserved flag bits set", 22);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_12, "Currently unsupported flags are set", 35);
extern NIM_CONST tyArray__TLfYrv9bhDLPrkLaYgjq2Ow crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58;
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_25, "Checksum verification failed", 28);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_27, "Size verification failed", 24);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_29, "Invalid compression info", 24);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_30, "Invalid header", 14);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_31, "Preset dictionary is not yet supported", 38);
STRING_LITERAL(TM__UqbkX1qqvV1mfEv19avhonw_32, "Unable to detect compressed data format", 39);
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch_system_5258;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_284)(NIM_CHAR* x, NI xLen_0, NIM_CHAR* y, NI yLen_0) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!!((xLen_0 == yLen_0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI f;
		NI colontmp_;
		NI res;
		f = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (xLen_0-1);
		res = ((NI) 0);
		{
			while (1) {
				NI TM__UqbkX1qqvV1mfEv19avhonw_2;
				if (!(res <= colontmp_)) goto LA7;
				f = res;
				{
					if ((NU)(f) >= (NU)(xLen_0)){ raiseIndexError2(f,xLen_0-1); }
					if ((NU)(f) >= (NU)(yLen_0)){ raiseIndexError2(f,yLen_0-1); }
					if (!!(((NU8)(x[f]) == (NU8)(y[f])))) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				if (nimAddInt(res, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_2)) { raiseOverflow(); };
				res = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_2);
			} LA7: ;
		}
	}
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NimStringDesc*, X5BX5D__pureZunicode_867)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM__UqbkX1qqvV1mfEv19avhonw_3;
	NI TM__UqbkX1qqvV1mfEv19avhonw_4;
	result = (NimStringDesc*)0;
	a = x.a;
	if (nimSubInt(x.b, a, &TM__UqbkX1qqvV1mfEv19avhonw_3)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__UqbkX1qqvV1mfEv19avhonw_3), ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_4)) { raiseOverflow(); };
	L = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_4);
	if ((L) < ((NI) 0) || (L) > ((NI) 2147483647)){ raiseRangeErrorI(L, ((NI) 0), ((NI) 2147483647)); }
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__UqbkX1qqvV1mfEv19avhonw_5;
				NI TM__UqbkX1qqvV1mfEv19avhonw_6;
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				if ((NU)(i) >= (NU)(result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (nimAddInt(i, a, &TM__UqbkX1qqvV1mfEv19avhonw_5)) { raiseOverflow(); };
				if ((NU)((NI)(TM__UqbkX1qqvV1mfEv19avhonw_5)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__UqbkX1qqvV1mfEv19avhonw_5),(s ? s->Sup.len : 0)-1); }
				result->data[i] = s->data[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_5)];
				if (nimAddInt(i_2, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_6)) { raiseOverflow(); };
				i_2 = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_6);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot__pureZunicode_842)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_system_5305((&gch_system_5258.zct), c);
}
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent__system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent__system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT_system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent__system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_system_5311(p);
	decRef_system_5356(T1_);
}
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent__system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_system_5311(src);
		incRef_system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_system_5311((*dest));
		decRef_system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(NI, nextZeroByte_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_198)(NimStringDesc* s, NI start) {
	NI result;
	tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T8_;
	NimStringDesc* T9_;
{	result = (NI)0;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (s ? s->Sup.len : 0);
		i_2 = start;
		{
			while (1) {
				NI TM__UqbkX1qqvV1mfEv19avhonw_13;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				{
					if ((NU)(i) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
					if (!((NU8)(s->data[i]) == (NU8)(0))) goto LA6_;
					result = i;
					goto BeforeRet_;
				}
				LA6_: ;
				if (nimAddInt(i_2, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_13)) { raiseOverflow(); };
				i_2 = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_13);
			} LA3: ;
		}
	}
	T8_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
	T8_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
	(*T8_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
	(*T8_).Sup.Sup.Sup.name = "ZippyError";
	T9_ = (NimStringDesc*)0;
	T9_ = (*T8_).Sup.Sup.Sup.message; (*T8_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
	if (T9_) nimGCunrefNoCycle(T9_);
	asgnRef((void**) (&(*T8_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T8_, "ZippyError", "nextZeroByte", "zippy.nim", 125);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187)(NimStringDesc* s, NI pos) {
	NU32 result;
	result = (NU32)0;
	result = (*((NU32*) ((&s->data[pos]))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_38)(NU32 v, NimStringDesc* data) {
	NU32 result;
	NI pos;
	result = (NU32)0;
	result = v;
	pos = (NI)0;
	{
		while (1) {
			NI TM__UqbkX1qqvV1mfEv19avhonw_21;
			NU32 one;
			NU32 T3_;
			NU32 two;
			NI TM__UqbkX1qqvV1mfEv19avhonw_22;
			NI TM__UqbkX1qqvV1mfEv19avhonw_23;
			if (nimSubInt((data ? data->Sup.len : 0), pos, &TM__UqbkX1qqvV1mfEv19avhonw_21)) { raiseOverflow(); };
			if (!(((NI) 8) <= (NI)(TM__UqbkX1qqvV1mfEv19avhonw_21))) goto LA2;
			T3_ = (NU32)0;
			T3_ = read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187(data, pos);
			one = (NU32)(T3_ ^ result);
			if (nimAddInt(pos, ((NI) 4), &TM__UqbkX1qqvV1mfEv19avhonw_22)) { raiseOverflow(); };
			two = read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187(data, (NI)(TM__UqbkX1qqvV1mfEv19avhonw_22));
			if ((NU)((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 0))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 0))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 8))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 8))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 16))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 16))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)(one) >> (NU32)(((NI) 24)))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)(one) >> (NU32)(((NI) 24))), 255); }
			if ((NU)((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 0))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 0))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 8))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 8))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 16))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 16))) & ((NU32) 255)), 255); }
			if ((NU)((NU32)((NU32)(two) >> (NU32)(((NI) 24)))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)(two) >> (NU32)(((NI) 24))), 255); }
			result = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 7))- 0][((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 0))) & ((NU32) 255)))- 0] ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 6))- 0][((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 8))) & ((NU32) 255)))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 5))- 0][((NU32)((NU32)((NU32)(one) >> (NU32)(((NI) 16))) & ((NU32) 255)))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 4))- 0][((NU32)((NU32)(one) >> (NU32)(((NI) 24))))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 3))- 0][((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 0))) & ((NU32) 255)))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 2))- 0][((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 8))) & ((NU32) 255)))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 1))- 0][((NU32)((NU32)((NU32)(two) >> (NU32)(((NI) 16))) & ((NU32) 255)))- 0]) ^ crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 0))- 0][((NU32)((NU32)(two) >> (NU32)(((NI) 24))))- 0]);
			if (nimAddInt(pos, ((NI) 8), &TM__UqbkX1qqvV1mfEv19avhonw_23)) { raiseOverflow(); };
			pos = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_23);
		} LA2: ;
	}
	{
		while (1) {
			NI TM__UqbkX1qqvV1mfEv19avhonw_24;
			if (!(pos < (data ? data->Sup.len : 0))) goto LA5;
			if ((NU)(pos) >= (NU)(data ? data->Sup.len : 0)){ raiseIndexError2(pos,(data ? data->Sup.len : 0)-1); }
			if ((NU)((NU32)((NU32)(result ^ ((NU32) (((NU8) (((NU8)(data->data[pos]))))))) & ((NU32) 255))) > (NU)(255)){ raiseIndexError2((NU32)((NU32)(result ^ ((NU32) (((NU8) (((NU8)(data->data[pos]))))))) & ((NU32) 255)), 255); }
			result = (NU32)(crcTables_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcrc_58[(((NI) 0))- 0][((NU32)((NU32)(result ^ ((NU32) (((NU8) (((NU8)(data->data[pos]))))))) & ((NU32) 255)))- 0] ^ (NU32)((NU32)(result) >> (NU32)(((NI) 8))));
			if (nimAddInt(pos, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_24)) { raiseOverflow(); };
			pos = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_24);
		} LA5: ;
	}
	return result;
}
static N_INLINE(NU32, crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_34)(NimStringDesc* data) {
	NU32 result;
	NU32 T1_;
	result = (NU32)0;
	T1_ = (NU32)0;
	T1_ = crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_38(((NU32) IL64(4294967295)), data);
	result = (NU32)((NU32) ~(T1_));
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D__system_7355)(NimStringDesc* s, NI i) {
	NIM_CHAR result;
	NI TM__UqbkX1qqvV1mfEv19avhonw_28;
	result = (NIM_CHAR)0;
	if (nimSubInt((s ? s->Sup.len : 0), i, &TM__UqbkX1qqvV1mfEv19avhonw_28)) { raiseOverflow(); };
	if ((NU)((NI)(TM__UqbkX1qqvV1mfEv19avhonw_28)) >= (NU)(s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__UqbkX1qqvV1mfEv19avhonw_28),(s ? s->Sup.len : 0)-1); }
	result = s->data[(NI)(TM__UqbkX1qqvV1mfEv19avhonw_28)];
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_165)(NimStringDesc** dst, NimStringDesc* src, tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA dataFormat) {
	switch (dataFormat) {
	case ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 2):
	{
		NU8 id1;
		NU8 id2;
		NU8 cm;
		NU8 flg;
		NIM_BOOL fhcrc;
		NIM_BOOL fextra;
		NIM_BOOL fname;
		NIM_BOOL fcomment;
		NI pos;
		NU32 checksum;
		NI TM__UqbkX1qqvV1mfEv19avhonw_19;
		NU32 isize;
		NI TM__UqbkX1qqvV1mfEv19avhonw_20;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T6_;
			NimStringDesc* T7_;
			if (!((src ? src->Sup.len : 0) < ((NI) 18))) goto LA4_;
			T6_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T6_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T6_).Sup.Sup.Sup.name = "ZippyError";
			T7_ = (NimStringDesc*)0;
			T7_ = (*T6_).Sup.Sup.Sup.message; (*T6_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
			if (T7_) nimGCunrefNoCycle(T7_);
			asgnRef((void**) (&(*T6_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T6_, "ZippyError", "uncompress", "zippy.nim", 94);
		}
		LA4_: ;
		if ((NU)(((NI) 0)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 0),(src ? src->Sup.len : 0)-1); }
		id1 = ((NU8) (((NU8)(src->data[((NI) 0)]))));
		if ((NU)(((NI) 1)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 1),(src ? src->Sup.len : 0)-1); }
		id2 = ((NU8) (((NU8)(src->data[((NI) 1)]))));
		if ((NU)(((NI) 2)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 2),(src ? src->Sup.len : 0)-1); }
		cm = ((NU8) (((NU8)(src->data[((NI) 2)]))));
		if ((NU)(((NI) 3)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 3),(src ? src->Sup.len : 0)-1); }
		flg = ((NU8) (((NU8)(src->data[((NI) 3)]))));
		{
			NIM_BOOL T10_;
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T14_;
			NimStringDesc* T15_;
			T10_ = (NIM_BOOL)0;
			T10_ = !((id1 == ((NU8) 31)));
			if (T10_) goto LA11_;
			T10_ = !((id2 == ((NU8) 139)));
			LA11_: ;
			if (!T10_) goto LA12_;
			T14_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T14_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T14_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T14_).Sup.Sup.Sup.name = "ZippyError";
			T15_ = (NimStringDesc*)0;
			T15_ = (*T14_).Sup.Sup.Sup.message; (*T14_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_9));
			if (T15_) nimGCunrefNoCycle(T15_);
			asgnRef((void**) (&(*T14_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T14_, "ZippyError", "uncompress", "zippy.nim", 106);
		}
		LA12_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T20_;
			NimStringDesc* T21_;
			if (!!((cm == ((NU8) 8)))) goto LA18_;
			T20_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T20_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T20_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T20_).Sup.Sup.Sup.name = "ZippyError";
			T21_ = (NimStringDesc*)0;
			T21_ = (*T20_).Sup.Sup.Sup.message; (*T20_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_10));
			if (T21_) nimGCunrefNoCycle(T21_);
			asgnRef((void**) (&(*T20_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T20_, "ZippyError", "uncompress", "zippy.nim", 108);
		}
		LA18_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T26_;
			NimStringDesc* T27_;
			if (!((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 224))))) goto LA24_;
			T26_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T26_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T26_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T26_).Sup.Sup.Sup.name = "ZippyError";
			T27_ = (NimStringDesc*)0;
			T27_ = (*T26_).Sup.Sup.Sup.message; (*T26_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_11));
			if (T27_) nimGCunrefNoCycle(T27_);
			asgnRef((void**) (&(*T26_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T26_, "ZippyError", "uncompress", "zippy.nim", 110);
		}
		LA24_: ;
		fhcrc = ((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 2))));
		fextra = ((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 4))));
		fname = ((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 8))));
		fcomment = ((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 16))));
		pos = ((NI) 10);
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T32_;
			NimStringDesc* T33_;
			if (!fextra) goto LA30_;
			T32_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T32_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T32_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T32_).Sup.Sup.Sup.name = "ZippyError";
			T33_ = (NimStringDesc*)0;
			T33_ = (*T32_).Sup.Sup.Sup.message; (*T32_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_12));
			if (T33_) nimGCunrefNoCycle(T33_);
			asgnRef((void**) (&(*T32_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T32_, "ZippyError", "uncompress", "zippy.nim", 128);
		}
		LA30_: ;
		{
			NI T38_;
			NI TM__UqbkX1qqvV1mfEv19avhonw_14;
			if (!fname) goto LA36_;
			T38_ = (NI)0;
			T38_ = nextZeroByte_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_198(src, pos);
			if (nimAddInt(T38_, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_14)) { raiseOverflow(); };
			pos = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_14);
		}
		LA36_: ;
		{
			NI T43_;
			NI TM__UqbkX1qqvV1mfEv19avhonw_15;
			if (!fcomment) goto LA41_;
			T43_ = (NI)0;
			T43_ = nextZeroByte_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_198(src, pos);
			if (nimAddInt(T43_, ((NI) 1), &TM__UqbkX1qqvV1mfEv19avhonw_15)) { raiseOverflow(); };
			pos = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_15);
		}
		LA41_: ;
		{
			NI TM__UqbkX1qqvV1mfEv19avhonw_17;
			if (!fhcrc) goto LA46_;
			{
				NI TM__UqbkX1qqvV1mfEv19avhonw_16;
				tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T52_;
				NimStringDesc* T53_;
				if (nimAddInt(pos, ((NI) 2), &TM__UqbkX1qqvV1mfEv19avhonw_16)) { raiseOverflow(); };
				if (!((src ? src->Sup.len : 0) <= (NI)(TM__UqbkX1qqvV1mfEv19avhonw_16))) goto LA50_;
				T52_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
				T52_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
				(*T52_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
				(*T52_).Sup.Sup.Sup.name = "ZippyError";
				T53_ = (NimStringDesc*)0;
				T53_ = (*T52_).Sup.Sup.Sup.message; (*T52_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
				if (T53_) nimGCunrefNoCycle(T53_);
				asgnRef((void**) (&(*T52_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
				raiseExceptionEx((Exception*)T52_, "ZippyError", "uncompress", "zippy.nim", 136);
			}
			LA50_: ;
			if (nimAddInt(pos, ((NI) 2), &TM__UqbkX1qqvV1mfEv19avhonw_17)) { raiseOverflow(); };
			pos = (NI)(TM__UqbkX1qqvV1mfEv19avhonw_17);
		}
		LA46_: ;
		{
			NI TM__UqbkX1qqvV1mfEv19avhonw_18;
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T58_;
			NimStringDesc* T59_;
			if (nimAddInt(pos, ((NI) 8), &TM__UqbkX1qqvV1mfEv19avhonw_18)) { raiseOverflow(); };
			if (!((src ? src->Sup.len : 0) <= (NI)(TM__UqbkX1qqvV1mfEv19avhonw_18))) goto LA56_;
			T58_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T58_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T58_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T58_).Sup.Sup.Sup.name = "ZippyError";
			T59_ = (NimStringDesc*)0;
			T59_ = (*T58_).Sup.Sup.Sup.message; (*T58_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
			if (T59_) nimGCunrefNoCycle(T59_);
			asgnRef((void**) (&(*T58_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T58_, "ZippyError", "uncompress", "zippy.nim", 144);
		}
		LA56_: ;
		if (nimSubInt((src ? src->Sup.len : 0), ((NI) 8), &TM__UqbkX1qqvV1mfEv19avhonw_19)) { raiseOverflow(); };
		checksum = read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187(src, (NI)(TM__UqbkX1qqvV1mfEv19avhonw_19));
		if (nimSubInt((src ? src->Sup.len : 0), ((NI) 4), &TM__UqbkX1qqvV1mfEv19avhonw_20)) { raiseOverflow(); };
		isize = read32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZlz5555_187(src, (NI)(TM__UqbkX1qqvV1mfEv19avhonw_20));
		inflate_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZinflate_478(dst, src, pos);
		{
			NU32 T62_;
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T65_;
			NimStringDesc* T66_;
			T62_ = (NU32)0;
			T62_ = crc32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_34((*dst));
			if (!!((checksum == T62_))) goto LA63_;
			T65_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T65_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T65_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T65_).Sup.Sup.Sup.name = "ZippyError";
			T66_ = (NimStringDesc*)0;
			T66_ = (*T65_).Sup.Sup.Sup.message; (*T65_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_25));
			if (T66_) nimGCunrefNoCycle(T66_);
			asgnRef((void**) (&(*T65_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T65_, "ZippyError", "uncompress", "zippy.nim", 154);
		}
		LA63_: ;
		{
			NI TM__UqbkX1qqvV1mfEv19avhonw_26;
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T71_;
			NimStringDesc* T72_;
			if (((NI) (-2147483647 -1)) == 0){ raiseDivByZero(); }
			if (nimModInt(((*dst) ? (*dst)->Sup.len : 0), ((NI) (-2147483647 -1)), &TM__UqbkX1qqvV1mfEv19avhonw_26)) { raiseOverflow(); };
			if (!!((isize == ((NU32) ((NI)(TM__UqbkX1qqvV1mfEv19avhonw_26)))))) goto LA69_;
			T71_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T71_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T71_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T71_).Sup.Sup.Sup.name = "ZippyError";
			T72_ = (NimStringDesc*)0;
			T72_ = (*T71_).Sup.Sup.Sup.message; (*T71_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_27));
			if (T72_) nimGCunrefNoCycle(T72_);
			asgnRef((void**) (&(*T71_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T71_, "ZippyError", "uncompress", "zippy.nim", 157);
		}
		LA69_: ;
	}
	break;
	case ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 1):
	{
		NU32 checksum_2;
		NIM_CHAR T80_;
		NIM_CHAR T81_;
		NIM_CHAR T82_;
		NIM_CHAR T83_;
		NU8 cmf;
		NU8 flg_2;
		NU8 cm_2;
		NU8 cinfo;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T78_;
			NimStringDesc* T79_;
			if (!((src ? src->Sup.len : 0) < ((NI) 6))) goto LA76_;
			T78_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T78_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T78_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T78_).Sup.Sup.Sup.name = "ZippyError";
			T79_ = (NimStringDesc*)0;
			T79_ = (*T78_).Sup.Sup.Sup.message; (*T78_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
			if (T79_) nimGCunrefNoCycle(T79_);
			asgnRef((void**) (&(*T78_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T78_, "ZippyError", "uncompress", "zippy.nim", 160);
		}
		LA76_: ;
		T80_ = (NIM_CHAR)0;
		T80_ = X5BX5D__system_7355(src, ((NI) 4));
		T81_ = (NIM_CHAR)0;
		T81_ = X5BX5D__system_7355(src, ((NI) 3));
		T82_ = (NIM_CHAR)0;
		T82_ = X5BX5D__system_7355(src, ((NI) 2));
		T83_ = (NIM_CHAR)0;
		T83_ = X5BX5D__system_7355(src, ((NI) 1));
		checksum_2 = (NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) (((NU8)(T80_))))) << (NU32)(((NI) 24))) | (NU32)((NU32)(((NU32) (((NU8)(T81_))))) << (NU32)(((NI) 16)))) | (NU32)((NU32)(((NU32) (((NU8)(T82_))))) << (NU32)(((NI) 8)))) | ((NU32) (((NU8)(T83_)))));
		if ((NU)(((NI) 0)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 0),(src ? src->Sup.len : 0)-1); }
		cmf = ((NU8) (((NU8)(src->data[((NI) 0)]))));
		if ((NU)(((NI) 1)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 1),(src ? src->Sup.len : 0)-1); }
		flg_2 = ((NU8) (((NU8)(src->data[((NI) 1)]))));
		cm_2 = (NU8)(cmf & ((NU8) 15));
		cinfo = (NU8)((NU8)(cmf) >> (NU32)(((NI) 4)));
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T88_;
			NimStringDesc* T89_;
			if (!!((cm_2 == ((NU8) 8)))) goto LA86_;
			T88_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T88_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T88_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T88_).Sup.Sup.Sup.name = "ZippyError";
			T89_ = (NimStringDesc*)0;
			T89_ = (*T88_).Sup.Sup.Sup.message; (*T88_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_10));
			if (T89_) nimGCunrefNoCycle(T89_);
			asgnRef((void**) (&(*T88_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T88_, "ZippyError", "uncompress", "zippy.nim", 176);
		}
		LA86_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T94_;
			NimStringDesc* T95_;
			if (!((NU8)(((NU8) 7)) < (NU8)(cinfo))) goto LA92_;
			T94_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T94_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T94_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T94_).Sup.Sup.Sup.name = "ZippyError";
			T95_ = (NimStringDesc*)0;
			T95_ = (*T94_).Sup.Sup.Sup.message; (*T94_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_29));
			if (T95_) nimGCunrefNoCycle(T95_);
			asgnRef((void**) (&(*T94_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T94_, "ZippyError", "uncompress", "zippy.nim", 178);
		}
		LA92_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T100_;
			NimStringDesc* T101_;
			if (!!(((NU16)((NU16)((NU16)((NU16)((NU16)((NU16)(((NU16) (cmf))) * (NU16)(((NU16) 256)))) + (NU16)(((NU16) (flg_2))))) % (NU16)(((NU16) 31))) == ((NU16) 0)))) goto LA98_;
			T100_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T100_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T100_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T100_).Sup.Sup.Sup.name = "ZippyError";
			T101_ = (NimStringDesc*)0;
			T101_ = (*T100_).Sup.Sup.Sup.message; (*T100_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_30));
			if (T101_) nimGCunrefNoCycle(T101_);
			asgnRef((void**) (&(*T100_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T100_, "ZippyError", "uncompress", "zippy.nim", 180);
		}
		LA98_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T106_;
			NimStringDesc* T107_;
			if (!!(((NU8)(flg_2 & ((NU8) 32)) == ((NU8) 0)))) goto LA104_;
			T106_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T106_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T106_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T106_).Sup.Sup.Sup.name = "ZippyError";
			T107_ = (NimStringDesc*)0;
			T107_ = (*T106_).Sup.Sup.Sup.message; (*T106_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_31));
			if (T107_) nimGCunrefNoCycle(T107_);
			asgnRef((void**) (&(*T106_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T106_, "ZippyError", "uncompress", "zippy.nim", 182);
		}
		LA104_: ;
		inflate_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZinflate_478(dst, src, ((NI) 2));
		{
			NU32 T110_;
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T113_;
			NimStringDesc* T114_;
			T110_ = (NU32)0;
			T110_ = adler32_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZcommon_584((*dst));
			if (!!((checksum_2 == T110_))) goto LA111_;
			T113_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T113_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T113_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T113_).Sup.Sup.Sup.name = "ZippyError";
			T114_ = (NimStringDesc*)0;
			T114_ = (*T113_).Sup.Sup.Sup.message; (*T113_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_25));
			if (T114_) nimGCunrefNoCycle(T114_);
			asgnRef((void**) (&(*T113_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T113_, "ZippyError", "uncompress", "zippy.nim", 187);
		}
		LA111_: ;
	}
	break;
	case ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 3):
	{
		inflate_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51ZzippyZinflate_478(dst, src, ((NI) 0));
	}
	break;
	case ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 0):
	{
		tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T117_;
		NimStringDesc* T118_;
		T117_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
		T117_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
		(*T117_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
		(*T117_).Sup.Sup.Sup.name = "ZippyError";
		T118_ = (NimStringDesc*)0;
		T118_ = (*T117_).Sup.Sup.Sup.message; (*T117_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_8));
		if (T118_) nimGCunrefNoCycle(T118_);
		asgnRef((void**) (&(*T117_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T117_, "ZippyError", "uncompress", "zippy.nim", 192);
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_262)(NimStringDesc* src, tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA dataFormat) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	if (((src ? src->Sup.len : 0)) < ((NI) 0) || ((src ? src->Sup.len : 0)) > ((NI) 2147483647)){ raiseRangeErrorI((src ? src->Sup.len : 0), ((NI) 0), ((NI) 2147483647)); }
	result = rawNewString(((NI) ((src ? src->Sup.len : 0))));
	switch (dataFormat) {
	case ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 0):
	{
		{
			NIM_BOOL T4_;
			NIM_BOOL T5_;
			tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T7_;
			NimStringDesc* T8_;
			T4_ = (NIM_BOOL)0;
			T5_ = (NIM_BOOL)0;
			T5_ = (((NI) 18) <= (src ? src->Sup.len : 0));
			if (!(T5_)) goto LA6_;
			T7_ = dotdot__pureZunicode_842(((NI) 0), ((NI) 2));
			T8_ = (NimStringDesc*)0;
			T8_ = X5BX5D__pureZunicode_867(src, T7_);
			T5_ = eqeq__6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_284(T8_->data, (T8_ ? T8_->Sup.len : 0), TM__UqbkX1qqvV1mfEv19avhonw_7, 3);
			LA6_: ;
			T4_ = T5_;
			if (!(T4_)) goto LA9_;
			if ((NU)(((NI) 3)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 3),(src ? src->Sup.len : 0)-1); }
			T4_ = ((NU8)(((NU8) (((NU8)(src->data[((NI) 3)])))) & ((NU8) 224)) == ((NU8) 0));
			LA9_: ;
			if (!T4_) goto LA10_;
			uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_165((&result), src, ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 2));
		}
		goto LA2_;
		LA10_: ;
		{
			NIM_BOOL T13_;
			NIM_BOOL T14_;
			NIM_BOOL T15_;
			T13_ = (NIM_BOOL)0;
			T14_ = (NIM_BOOL)0;
			T15_ = (NIM_BOOL)0;
			T15_ = (((NI) 6) <= (src ? src->Sup.len : 0));
			if (!(T15_)) goto LA16_;
			if ((NU)(((NI) 0)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 0),(src ? src->Sup.len : 0)-1); }
			T15_ = ((NU8)(((NU8) (((NU8)(src->data[((NI) 0)])))) & ((NU8) 15)) == ((NU8) 8));
			LA16_: ;
			T14_ = T15_;
			if (!(T14_)) goto LA17_;
			if ((NU)(((NI) 0)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 0),(src ? src->Sup.len : 0)-1); }
			T14_ = ((NU8)((NU8)((NU8)(((NU8) (((NU8)(src->data[((NI) 0)]))))) >> (NU32)(((NI) 4)))) <= (NU8)(((NU8) 7)));
			LA17_: ;
			T13_ = T14_;
			if (!(T13_)) goto LA18_;
			if ((NU)(((NI) 0)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 0),(src ? src->Sup.len : 0)-1); }
			if ((NU)(((NI) 1)) >= (NU)(src ? src->Sup.len : 0)){ raiseIndexError2(((NI) 1),(src ? src->Sup.len : 0)-1); }
			T13_ = ((NU16)((NU16)((NU16)((NU16)((NU16)((NU16)(((NU16) (((NU8)(src->data[((NI) 0)]))))) * (NU16)(((NU16) 256)))) + (NU16)(((NU16) (((NU8)(src->data[((NI) 1)]))))))) % (NU16)(((NU16) 31))) == ((NU16) 0));
			LA18_: ;
			if (!T13_) goto LA19_;
			uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_165((&result), src, ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 1));
		}
		goto LA2_;
		LA19_: ;
		{
			tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg* T22_;
			NimStringDesc* T23_;
			T22_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*)0;
			T22_ = (tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg*) newObj((&NTIrefzippyerror__da4gLSgMwOCwCaJSZe17sg_), sizeof(tyObject_ZippyError__cuFDdsiUF1yWdvcbJ19aijg));
			(*T22_).Sup.Sup.Sup.Sup.m_type = (&NTIzippyerror__cuFDdsiUF1yWdvcbJ19aijg_);
			(*T22_).Sup.Sup.Sup.name = "ZippyError";
			T23_ = (NimStringDesc*)0;
			T23_ = (*T22_).Sup.Sup.Sup.message; (*T22_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__UqbkX1qqvV1mfEv19avhonw_32));
			if (T23_) nimGCunrefNoCycle(T23_);
			asgnRef((void**) (&(*T22_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T22_, "ZippyError", "uncompress", "zippy.nim", 218);
		}
		LA2_: ;
	}
	break;
	default:
	{
		uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_165((&result), src, dataFormat);
	}
	break;
	}
	return result;
}
