/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA;
typedef struct tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw;
typedef struct tyObject_ICLRRuntimeInfo__XOK1J81FSgMkvppKAUt1Gg tyObject_ICLRRuntimeInfo__XOK1J81FSgMkvppKAUt1Gg;
typedef struct tyObject_IUnknownVtbl__jF4R4hWZYkQD9a5uVek42vg tyObject_IUnknownVtbl__jF4R4hWZYkQD9a5uVek42vg;
typedef struct tyObject_ICLRMetaHost__So9cXMr4GeP1oduG9cGayd9bg tyObject_ICLRMetaHost__So9cXMr4GeP1oduG9cGayd9bg;
typedef struct tyObject_IObject__gduWP00sjbqVCHdPpDHXqQ tyObject_IObject__gduWP00sjbqVCHdPpDHXqQ;
typedef struct tyObject_IType__WzRXfD2eolvABGMHb5N5Sg tyObject_IType__WzRXfD2eolvABGMHb5N5Sg;
typedef struct tyObject_ICLRRuntimeHost__ENRFsRz7mXWHd9apxd9agfpw tyObject_ICLRRuntimeHost__ENRFsRz7mXWHd9apxd9agfpw;
typedef struct tyObject_ICorRuntimeHost__hApx39bWkLexEr3KhO3ZqUg tyObject_ICorRuntimeHost__hApx39bWkLexEr3KhO3ZqUg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc__QOiFtZpE8c3zN4C9aqU9blOA) (tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA* clsid, tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA* riid, void** ppInterface);
struct tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw {
tyObject_IUnknownVtbl__jF4R4hWZYkQD9a5uVek42vg* lpVtbl;
};
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
STRING_LITERAL(TM__2fXpvVip9cz2du6iLB2sfOw_4, "mscoree", 7);
STRING_LITERAL(TM__2fXpvVip9cz2du6iLB2sfOw_5, "mscoree", 7);
static void* TM__2fXpvVip9cz2du6iLB2sfOw_2;
tyProc__QOiFtZpE8c3zN4C9aqU9blOA Dl_81792513_;
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterICLRRuntimeInfoToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7187)(tyObject_ICLRRuntimeInfo__XOK1J81FSgMkvppKAUt1Gg* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterICLRMetaHostToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7172)(tyObject_ICLRMetaHost__So9cXMr4GeP1oduG9cGayd9bg* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterIObjectToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7202)(tyObject_IObject__gduWP00sjbqVCHdPpDHXqQ* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterITypeToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7205)(tyObject_IType__WzRXfD2eolvABGMHb5N5Sg* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterICLRRuntimeHostToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7136)(tyObject_ICLRRuntimeHost__ENRFsRz7mXWHd9apxd9agfpw* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*, winimConverterICorRuntimeHostToIUnknown_6758Z85sersZxZOnimbleZpkgsZwinim4551O55O49ZwinimZincZmscoree_7004)(tyObject_ICorRuntimeHost__hApx39bWkLexEr3KhO3ZqUg* x) {
	tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw* result;
	result = (tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*)0;
	result = ((tyObject_IUnknown__GaCOTm3fAeQng3LkqGK9cpw*) (x));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, winim_mscoreeDatInit000)(void) {
if (!((TM__2fXpvVip9cz2du6iLB2sfOw_2 = nimLoadLibrary(((NimStringDesc*) &TM__2fXpvVip9cz2du6iLB2sfOw_4)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__2fXpvVip9cz2du6iLB2sfOw_5));
	Dl_81792513_ = (tyProc__QOiFtZpE8c3zN4C9aqU9blOA) nimGetProcAddr(TM__2fXpvVip9cz2du6iLB2sfOw_2, "CLRCreateInstance");
}

