/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc__BPQkGXZ9bepMVJITTbu8UUg) (tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA* rguid1, tyObject_GUID__vR9aKCQzKs1RAi9cxPq9bGGlA* rguid2);
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
STRING_LITERAL(TM__Az9aStCqZyHdXRb5O9bpGz9bw_4, "ole32", 5);
STRING_LITERAL(TM__Az9aStCqZyHdXRb5O9bpGz9bw_5, "ole32", 5);
N_LIB_PRIVATE TNimType NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_;
N_LIB_PRIVATE TNimType NTIbyte__k3HXouOuhqAKq0dx450lXQ_;
N_LIB_PRIVATE TNimType NTIshort__kDPg4wXyR8DDyA0MeEjIsw_;
N_LIB_PRIVATE TNimType NTIfloat__C875xFvYpI7aGybrDGHIaQ_;
N_LIB_PRIVATE TNimType NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTIvartype__M4na42GvebBMnI5wV9cYMxg_;
N_LIB_PRIVATE TNimType NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_;
N_LIB_PRIVATE TNimType NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_;
N_LIB_PRIVATE TNimType NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_;
extern TNimType NTIint5150__sVg18TP9cLifHyygRe9cro9aA_;
N_LIB_PRIVATE TNimType NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_;
N_LIB_PRIVATE TNimType NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_;
N_LIB_PRIVATE TNimType NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_;
N_LIB_PRIVATE TNimType NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_;
N_LIB_PRIVATE TNimType NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_;
N_LIB_PRIVATE TNimType NTIchar__nmiMWKVIe46vacnhAFrQvw_;
N_LIB_PRIVATE TNimType NTIptrchar__9b60r3P3z08159cCfYvgtoSg_;
static void* TM__Az9aStCqZyHdXRb5O9bpGz9bw_2;
tyProc__BPQkGXZ9bepMVJITTbu8UUg Dl_128984050_;
N_LIB_PRIVATE N_NIMCALL(void, winim_windefDatInit000)(void) {
NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_.size = sizeof(NI64);
NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_.align = NIM_ALIGNOF(NI64);
NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_.kind = 35;
NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_.base = 0;
NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_.flags = 3;
NTIbyte__k3HXouOuhqAKq0dx450lXQ_.size = sizeof(NU8);
NTIbyte__k3HXouOuhqAKq0dx450lXQ_.align = NIM_ALIGNOF(NU8);
NTIbyte__k3HXouOuhqAKq0dx450lXQ_.kind = 41;
NTIbyte__k3HXouOuhqAKq0dx450lXQ_.base = 0;
NTIbyte__k3HXouOuhqAKq0dx450lXQ_.flags = 3;
NTIshort__kDPg4wXyR8DDyA0MeEjIsw_.size = sizeof(NI16);
NTIshort__kDPg4wXyR8DDyA0MeEjIsw_.align = NIM_ALIGNOF(NI16);
NTIshort__kDPg4wXyR8DDyA0MeEjIsw_.kind = 33;
NTIshort__kDPg4wXyR8DDyA0MeEjIsw_.base = 0;
NTIshort__kDPg4wXyR8DDyA0MeEjIsw_.flags = 3;
NTIfloat__C875xFvYpI7aGybrDGHIaQ_.size = sizeof(NF32);
NTIfloat__C875xFvYpI7aGybrDGHIaQ_.align = NIM_ALIGNOF(NF32);
NTIfloat__C875xFvYpI7aGybrDGHIaQ_.kind = 37;
NTIfloat__C875xFvYpI7aGybrDGHIaQ_.base = 0;
NTIfloat__C875xFvYpI7aGybrDGHIaQ_.flags = 3;
NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_.size = sizeof(NF);
NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_.align = NIM_ALIGNOF(NF);
NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_.kind = 36;
NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_.base = 0;
NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_.flags = 3;
NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_.size = sizeof(NU16*);
NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_.align = NIM_ALIGNOF(NU16*);
NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_.kind = 21;
NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_.base = (&NTIvartype__M4na42GvebBMnI5wV9cYMxg_);
NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_.flags = 3;
NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_.size = sizeof(NU8*);
NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_.align = NIM_ALIGNOF(NU8*);
NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_.kind = 21;
NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_.base = (&NTIbyte__k3HXouOuhqAKq0dx450lXQ_);
NTIptrbyte__cG1a2XAxsP28AUq2q9aXnNg_.flags = 3;
NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_.size = sizeof(NI16*);
NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_.align = NIM_ALIGNOF(NI16*);
NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_.kind = 21;
NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_.base = (&NTIshort__kDPg4wXyR8DDyA0MeEjIsw_);
NTIptrshort__BjHmAJOH9agj4KRxOkanazQ_.flags = 3;
NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_.size = sizeof(NI32*);
NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_.align = NIM_ALIGNOF(NI32*);
NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_.kind = 21;
NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_.base = (&NTIint5150__sVg18TP9cLifHyygRe9cro9aA_);
NTIptrlong__9awHbpuyuG8AxbsaqeBLKDQ_.flags = 3;
NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_.size = sizeof(NI64*);
NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_.align = NIM_ALIGNOF(NI64*);
NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_.kind = 21;
NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_.base = (&NTIlonglong__Aav8dQoMlCFnZRxA0IhTHQ_);
NTIptrlonglong__qTZjETMuYhaATb9arhin3WA_.flags = 3;
NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_.size = sizeof(NF32*);
NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_.align = NIM_ALIGNOF(NF32*);
NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_.kind = 21;
NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_.base = (&NTIfloat__C875xFvYpI7aGybrDGHIaQ_);
NTIptrfloat__K9c5mNCKsxyPa9bhQF1Un42w_.flags = 3;
NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_.size = sizeof(NF*);
NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_.align = NIM_ALIGNOF(NF*);
NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_.kind = 21;
NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_.base = (&NTIdouble__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTIptrdouble__dHulNBWhJTS79cd5h9cp4OHg_.flags = 3;
NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_.size = sizeof(NU16**);
NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_.align = NIM_ALIGNOF(NU16**);
NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_.kind = 21;
NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_.base = (&NTIptrolechar__9arplNu1iE9bhlDxcL6A4PMw_);
NTIptrbstr__Pdw3MEiEie9cIIBXdRF4aZg_.flags = 3;
NTIchar__nmiMWKVIe46vacnhAFrQvw_.size = sizeof(NIM_CHAR);
NTIchar__nmiMWKVIe46vacnhAFrQvw_.align = NIM_ALIGNOF(NIM_CHAR);
NTIchar__nmiMWKVIe46vacnhAFrQvw_.kind = 2;
NTIchar__nmiMWKVIe46vacnhAFrQvw_.base = 0;
NTIchar__nmiMWKVIe46vacnhAFrQvw_.flags = 3;
NTIptrchar__9b60r3P3z08159cCfYvgtoSg_.size = sizeof(NIM_CHAR*);
NTIptrchar__9b60r3P3z08159cCfYvgtoSg_.align = NIM_ALIGNOF(NIM_CHAR*);
NTIptrchar__9b60r3P3z08159cCfYvgtoSg_.kind = 21;
NTIptrchar__9b60r3P3z08159cCfYvgtoSg_.base = (&NTIchar__nmiMWKVIe46vacnhAFrQvw_);
NTIptrchar__9b60r3P3z08159cCfYvgtoSg_.flags = 3;
if (!((TM__Az9aStCqZyHdXRb5O9bpGz9bw_2 = nimLoadLibrary(((NimStringDesc*) &TM__Az9aStCqZyHdXRb5O9bpGz9bw_4)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__Az9aStCqZyHdXRb5O9bpGz9bw_5));
	Dl_128984050_ = (tyProc__BPQkGXZ9bepMVJITTbu8UUg) nimGetProcAddr(TM__Az9aStCqZyHdXRb5O9bpGz9bw_2, "IsEqualGUID");
}

