/* Generated by Nim Compiler v1.6.0 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__wfzhy8RTNYkMytxQXIPT1A tySequence__wfzhy8RTNYkMytxQXIPT1A;
typedef struct tyObject_Header__oFhWnxD33zTQi87OVhvcHw tyObject_Header__oFhWnxD33zTQi87OVhvcHw;
typedef struct tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA;
typedef struct tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ;
typedef struct tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Header__oFhWnxD33zTQi87OVhvcHw {
NimStringDesc* key;
NimStringDesc* value;
};
struct tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA {
tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url;
tySequence__wfzhy8RTNYkMytxQXIPT1A* headers;
NF32 timeout;
NimStringDesc* verb;
NimStringDesc* body;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* fragment;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* paths;
tySequence__4eQHGndY6XBYpFOH09apV8Q* query;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray__Re75IspeoxXy2oCZHwcRrA[2];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA {
  tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw Sup;
};
struct tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ {
tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url;
tySequence__wfzhy8RTNYkMytxQXIPT1A* headers;
NI code;
NimStringDesc* body;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef N_STDCALL_PTR(void*, tyProc__81VIzYkqwzDl7rl3af0pZg) (NU16* lpszAgent, NI32 dwAccessType, NU16* lpszProxy, NU16* lpszProxyBypass, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc__Jf1Ud3fyK3FJ9a0p2hXD9akg) (void* hSession, NI32 nResolveTimeout, NI32 nConnectTimeout, NI32 nSendTimeout, NI32 nReceiveTimeout);
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef N_STDCALL_PTR(void*, tyProc__RFwzZ679c39c5tm4O7Tpzjeg) (void* hSession, NU16* lpszServerName, NU16 nServerPort, NI32 dwFlags);
typedef NU16* tyArray__0A3IEb7UFsBrsbktr2qWew[2];
typedef N_STDCALL_PTR(void*, tyProc__VvL5F9ctiPFd9cY0CxFJmncg) (void* hConnect, NU16* lpszVerb, NU16* lpszObjectName, NU16* lpszVersion, NU16* lpszReferrer, NU16** lplpszAcceptTypes, NI32 dwFlags);
typedef N_STDCALL_PTR(NI32, tyProc__GDtgFkYwnC8EJx7gppgoYg) (void* hRequest, NU16* lpszHeaders, NI32 dwHeadersLength, NI32 dwModifiers);
typedef N_STDCALL_PTR(NI32, tyProc__aux9clEFrOZ9cb4mZ9cYQop4g) (void* hRequest, NU16* lpszHeaders, NI32 dwHeadersLength, void* lpOptional, NI32 dwOptionalLength, NI32 dwTotalLength, NU32 dwContext);
typedef N_STDCALL_PTR(NI32, tyProc__wS8JrJMcfFBzgzuqJGOAAg) (void* hRequest, void* lpReserved);
typedef N_STDCALL_PTR(NI32, tyProc__5V5gHAr7e9bsH0OKztxYmCw) (void* hRequest, NI32 dwInfoLevel, NU16* pwszName, void* lpBuffer, NI32* lpdwBufferLength, NI32* lpdwIndex);
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef N_STDCALL_PTR(NI32, tyProc__mID4zaJ5rXbvlxUmzwPGLw) (void* hFile, void* lpBuffer, NI32 dwNumberOfBytesToRead, NI32* lpdwNumberOfBytesRead);
typedef NU8 tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA;
typedef N_STDCALL_PTR(NI32, tyProc__ah5wcFv3UG20t2vgXBy0Fg) (void* hInternet);
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__wfzhy8RTNYkMytxQXIPT1A {
  TGenericSeq Sup;
  tyObject_Header__oFhWnxD33zTQi87OVhvcHw data[SEQ_DECL_SIZE];
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  TGenericSeq Sup;
  NU16 data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*, newRequest_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_305)(NimStringDesc* url, NimStringDesc* verb, tySequence__wfzhy8RTNYkMytxQXIPT1A* headers, NF32 timeout);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__wfzhy8RTNYkMytxQXIPT1A)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__PnYa0s029a36UKFZ9c9bwgo8g)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg*, parseUrl_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_214)(NimStringDesc* s);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr);
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y);
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, merge_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_134)(tySequence__wfzhy8RTNYkMytxQXIPT1A** a, tySequence__wfzhy8RTNYkMytxQXIPT1A* b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*, fetch_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_154)(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* req);
static N_INLINE(NIM_BOOL, contains_stdZenumutils_43)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_stdZenumutils_48)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_NIMCALL(void, Marker_tyRef__dOa7PNltuukzDKey55t7hw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, addDefaultHeaders_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_150)(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* req);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23)(tySequence__wfzhy8RTNYkMytxQXIPT1A* headers, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_67)(tySequence__wfzhy8RTNYkMytxQXIPT1A** headers, NimStringDesc* key, NimStringDesc* value);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(tySequence__uFLLGQVsiasALrzzzvqnZw*, toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3)(NimStringDesc* input);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, path_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_542)(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, search_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_506)(tyObject_UrlcolonObjectType___BLDUGAmrTNcm5NpX5hztCg* url);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToUpperAsciiStr)(NimStringDesc* s);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, setLengthSeqV2)(TGenericSeq* s, TNimType* typ, NI newLen);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toUtf8_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_27)(tySequence__uFLLGQVsiasALrzzzvqnZw* input);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_262)(NimStringDesc* src, tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA dataFormat);
N_LIB_PRIVATE N_NIMCALL(void, nimLeaveFinally)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE TNimType NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_;
extern TNimType NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_;
N_LIB_PRIVATE TNimType NTIheader__oFhWnxD33zTQi87OVhvcHw_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_;
extern TNimType NTIfloat__C875xFvYpI7aGybrDGHIaQ_;
N_LIB_PRIVATE TNimType NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_5, "iterators.nim(249, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_7, "iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_8, "get", 3);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_12, "http", 4);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_13, "https", 5);
static NIM_CONST tyArray__Re75IspeoxXy2oCZHwcRrA TM__qSKfopWphFR2T9ctNAOgqbQ_11 = {((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_12),
((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_13)}
;
extern TNimType NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_;
extern TNimType NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_14, "Unsupported request scheme: ", 28);
N_LIB_PRIVATE TNimType NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIresponse__dOa7PNltuukzDKey55t7hw_;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_17, "user-agent", 10);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_19, "Puppy", 5);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_20, "accept-encoding", 15);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_21, "gzip", 4);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_23, "WinHttpOpen error: ", 19);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_24, "WinHttpSetTimeouts error: ", 26);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_26, "Invalid port: ", 14);
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_27, "Parsing port failed", 19);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_28, "WinHttpConnect error: ", 22);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_29, "\?", 1);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_30, "*/*", 3);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_31, "WinHttpOpenRequest error: ", 26);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_32, ": ", 2);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_33, "\015\012", 2);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_35, "WinHttpAddRequestHeaders error: ", 32);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_36, "WinHttpSendRequest error: ", 26);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_37, "WinHttpReceiveResponse error: ", 30);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_38, "WinHttpQueryHeaders error: ", 27);
extern TNimType NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_41, "HttpQueryInfoW error: ", 22);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_42, "Error parsing response headers", 30);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_43, ":", 1);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__qSKfopWphFR2T9ctNAOgqbQ_44 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_46, "iterators.nim(173, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_48, "WinHttpReadData error: ", 23);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_52, "content-encoding", 16);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_53, "Non 200 response code: ", 23);
STRING_LITERAL(TM__qSKfopWphFR2T9ctNAOgqbQ_54, "\012", 1);
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch_system_5258;
extern TSafePoint* excHandler_system_2567;
extern TSafePoint* excHandler_system_2567;
extern tyProc__81VIzYkqwzDl7rl3af0pZg Dl_121634853_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_121634843_;
extern tyProc__Jf1Ud3fyK3FJ9a0p2hXD9akg Dl_121634859_;
extern TSafePoint* excHandler_system_2567;
extern TSafePoint* excHandler_system_2567;
extern Exception* currException_system_2568;
extern Exception* currException_system_2568;
extern Exception* currException_system_2568;
extern Exception* currException_system_2568;
extern tyProc__RFwzZ679c39c5tm4O7Tpzjeg Dl_121634865_;
extern tyProc__VvL5F9ctiPFd9cY0CxFJmncg Dl_121634870_;
extern tyProc__GDtgFkYwnC8EJx7gppgoYg Dl_121634878_;
extern tyProc__aux9clEFrOZ9cb4mZ9cYQop4g Dl_121634883_;
extern tyProc__wS8JrJMcfFBzgzuqJGOAAg Dl_121634891_;
extern tyProc__5V5gHAr7e9bsH0OKztxYmCw Dl_121634894_;
extern tyProc__mID4zaJ5rXbvlxUmzwPGLw Dl_121634901_;
extern tyProc__ah5wcFv3UG20t2vgXBy0Fg Dl_121634906_;
static N_NIMCALL(void, Marker_tySequence__wfzhy8RTNYkMytxQXIPT1A)(void* p, NI op) {
	tySequence__wfzhy8RTNYkMytxQXIPT1A* a;
	NI T1_;
	a = (tySequence__wfzhy8RTNYkMytxQXIPT1A*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].key, op);
	nimGCvisit((void*)a->data[T1_].value, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__PnYa0s029a36UKFZ9c9bwgo8g)(void* p, NI op) {
	tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* a;
	a = (tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*)p;
	nimGCvisit((void*)(*a).url, op);
	nimGCvisit((void*)(*a).headers, op);
	nimGCvisit((void*)(*a).verb, op);
	nimGCvisit((void*)(*a).body, op);
}
static N_INLINE(NI, pluspercent__system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef_system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent__system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent__system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent__system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent__system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT_system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_system_5305((&gch_system_5258.zct), c);
}
static N_INLINE(void, decRef_system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent__system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent__system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT_system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_system_5311(src);
		incRef_system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_system_5311((*dest));
		decRef_system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_system_5311(p);
	decRef_system_5356(T1_);
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem_system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a ? a->Sup.len : 0);
	blen = (b ? b->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem_system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, merge_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_134)(tySequence__wfzhy8RTNYkMytxQXIPT1A** a, tySequence__wfzhy8RTNYkMytxQXIPT1A* b) {
	{
		tyObject_Header__oFhWnxD33zTQi87OVhvcHw* headerB;
		NI i;
		NI L;
		NI T2_;
		headerB = (tyObject_Header__oFhWnxD33zTQi87OVhvcHw*)0;
		i = ((NI) 0);
		T2_ = (b ? b->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NIM_BOOL found;
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_6;
				if (!(i < L)) goto LA4;
				if ((NU)(i) >= (NU)(b ? b->Sup.len : 0)){ raiseIndexError2(i,(b ? b->Sup.len : 0)-1); }
				headerB = (&b->data[i]);
				found = NIM_FALSE;
				{
					tyObject_Header__oFhWnxD33zTQi87OVhvcHw* headerA;
					NI i_2;
					NI L_2;
					NI T6_;
					headerA = (tyObject_Header__oFhWnxD33zTQi87OVhvcHw*)0;
					i_2 = ((NI) 0);
					T6_ = ((*a) ? (*a)->Sup.len : 0);
					L_2 = T6_;
					{
						while (1) {
							NI TM__qSKfopWphFR2T9ctNAOgqbQ_4;
							if (!(i_2 < L_2)) goto LA8;
							if ((NU)(i_2) >= (NU)((*a) ? (*a)->Sup.len : 0)){ raiseIndexError2(i_2,((*a) ? (*a)->Sup.len : 0)-1); }
							headerA = (&(*a)->data[i_2]);
							{
								NimStringDesc* T11_;
								NimStringDesc* T12_;
								T11_ = (NimStringDesc*)0;
								T11_ = nsuToLowerAsciiStr((*headerA).key);
								T12_ = (NimStringDesc*)0;
								T12_ = nsuToLowerAsciiStr((*headerB).key);
								if (!eqStrings(T11_, T12_)) goto LA13_;
								unsureAsgnRef((void**) (&(*headerA).value), copyString((*headerB).value));
								found = NIM_TRUE;
							}
							LA13_: ;
							if (nimAddInt(i_2, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_4)) { raiseOverflow(); };
							i_2 = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_4);
							{
								NI T17_;
								T17_ = ((*a) ? (*a)->Sup.len : 0);
								if (!!((T17_ == L_2))) goto LA18_;
								failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_5));
							}
							LA18_: ;
						} LA8: ;
					}
				}
				{
					NI T24_;
					NimStringDesc* T25_;
					NimStringDesc* T26_;
					if (!!(found)) goto LA22_;
					unsureAsgnRef((void**) (&(*a)), (tySequence__wfzhy8RTNYkMytxQXIPT1A*) incrSeqV3((TGenericSeq*)((*a)), (&NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_)));
					T24_ = (*a)->Sup.len++;
					T25_ = (NimStringDesc*)0;
					T25_ = (*a)->data[T24_].key; (*a)->data[T24_].key = copyStringRC1((*headerB).key);
					if (T25_) nimGCunrefNoCycle(T25_);
					T26_ = (NimStringDesc*)0;
					T26_ = (*a)->data[T24_].value; (*a)->data[T24_].value = copyStringRC1((*headerB).value);
					if (T26_) nimGCunrefNoCycle(T26_);
				}
				LA22_: ;
				if (nimAddInt(i, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_6)) { raiseOverflow(); };
				i = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_6);
				{
					NI T29_;
					T29_ = (b ? b->Sup.len : 0);
					if (!!((T29_ == L))) goto LA30_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_7));
				}
				LA30_: ;
			} LA4: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*, newRequest_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_305)(NimStringDesc* url, NimStringDesc* verb, tySequence__wfzhy8RTNYkMytxQXIPT1A* headers, NF32 timeout) {
	tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* result;
	tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* T1_;
	NimStringDesc* T2_;
	result = (tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*)0;
	T1_ = (tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*)0;
	T1_ = (tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*) newObj((&NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_), sizeof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA));
	result = T1_;
	asgnRef((void**) (&(*result).url), parseUrl_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_214(url));
	T2_ = (NimStringDesc*)0;
	T2_ = (*result).verb; (*result).verb = copyStringRC1(verb);
	if (T2_) nimGCunrefNoCycle(T2_);
	merge_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_134((&(*result).headers), headers);
	(*result).timeout = timeout;
	return result;
}
static N_INLINE(NI, find_stdZenumutils_48)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		NimStringDesc** i;
		NI i_2;
		i = (NimStringDesc**)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_9;
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_10;
				if (!(i_2 < aLen_0)) goto LA3;
				if ((NU)(i_2) >= (NU)(aLen_0)){ raiseIndexError2(i_2,aLen_0-1); }
				i = (&a[i_2]);
				{
					if (!eqStrings((*i), item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				if (nimAddInt(result, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_9)) { raiseOverflow(); };
				result = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_9);
				if (nimAddInt(i_2, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_10)) { raiseOverflow(); };
				i_2 = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_10);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains_stdZenumutils_43)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find_stdZenumutils_48(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem_system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem_system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_NIMCALL(void, Marker_tyRef__dOa7PNltuukzDKey55t7hw)(void* p, NI op) {
	tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ* a;
	a = (tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*)p;
	nimGCvisit((void*)(*a).url, op);
	nimGCvisit((void*)(*a).headers, op);
	nimGCvisit((void*)(*a).body, op);
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23)(tySequence__wfzhy8RTNYkMytxQXIPT1A* headers, NimStringDesc* key) {
	NimStringDesc* result;
{	result = (NimStringDesc*)0;
	{
		tyObject_Header__oFhWnxD33zTQi87OVhvcHw* header;
		NI i;
		NI L;
		NI T2_;
		header = (tyObject_Header__oFhWnxD33zTQi87OVhvcHw*)0;
		i = ((NI) 0);
		T2_ = (headers ? headers->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_16;
				if (!(i < L)) goto LA4;
				if ((NU)(i) >= (NU)(headers ? headers->Sup.len : 0)){ raiseIndexError2(i,(headers ? headers->Sup.len : 0)-1); }
				header = (&headers->data[i]);
				{
					NimStringDesc* T7_;
					NimStringDesc* T8_;
					T7_ = (NimStringDesc*)0;
					T7_ = nsuToLowerAsciiStr((*header).key);
					T8_ = (NimStringDesc*)0;
					T8_ = nsuToLowerAsciiStr(key);
					if (!eqStrings(T7_, T8_)) goto LA9_;
					result = copyString((*header).value);
					goto BeforeRet_;
				}
				LA9_: ;
				if (nimAddInt(i, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_16)) { raiseOverflow(); };
				i = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_16);
				{
					NI T13_;
					T13_ = (headers ? headers->Sup.len : 0);
					if (!!((T13_ == L))) goto LA14_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_7));
				}
				LA14_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem_systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_67)(tySequence__wfzhy8RTNYkMytxQXIPT1A** headers, NimStringDesc* key, NimStringDesc* value) {
	tyObject_Header__oFhWnxD33zTQi87OVhvcHw T16_;
	NI T17_;
	NimStringDesc* T18_;
	NimStringDesc* T19_;
{	{
		tyObject_Header__oFhWnxD33zTQi87OVhvcHw* header;
		NI i;
		NI L;
		NI T2_;
		header = (tyObject_Header__oFhWnxD33zTQi87OVhvcHw*)0;
		i = ((NI) 0);
		T2_ = ((*headers) ? (*headers)->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_18;
				if (!(i < L)) goto LA4;
				if ((NU)(i) >= (NU)((*headers) ? (*headers)->Sup.len : 0)){ raiseIndexError2(i,((*headers) ? (*headers)->Sup.len : 0)-1); }
				header = (&(*headers)->data[i]);
				{
					NimStringDesc* T7_;
					NimStringDesc* T8_;
					T7_ = (NimStringDesc*)0;
					T7_ = nsuToLowerAsciiStr((*header).key);
					T8_ = (NimStringDesc*)0;
					T8_ = nsuToLowerAsciiStr(key);
					if (!eqStrings(T7_, T8_)) goto LA9_;
					unsureAsgnRef((void**) (&(*header).value), copyString(value));
					goto BeforeRet_;
				}
				LA9_: ;
				if (nimAddInt(i, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_18)) { raiseOverflow(); };
				i = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_18);
				{
					NI T13_;
					T13_ = ((*headers) ? (*headers)->Sup.len : 0);
					if (!!((T13_ == L))) goto LA14_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_5));
				}
				LA14_: ;
			} LA4: ;
		}
	}
	nimZeroMem((void*)(&T16_), sizeof(tyObject_Header__oFhWnxD33zTQi87OVhvcHw));
	nimZeroMem((void*)(&T16_), sizeof(tyObject_Header__oFhWnxD33zTQi87OVhvcHw));
	T16_.key = copyString(key);
	T16_.value = copyString(value);
	unsureAsgnRef((void**) (&(*headers)), (tySequence__wfzhy8RTNYkMytxQXIPT1A*) incrSeqV3((TGenericSeq*)((*headers)), (&NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_)));
	T17_ = (*headers)->Sup.len++;
	T18_ = (NimStringDesc*)0;
	T18_ = (*headers)->data[T17_].key; (*headers)->data[T17_].key = copyStringRC1(T16_.key);
	if (T18_) nimGCunrefNoCycle(T18_);
	T19_ = (NimStringDesc*)0;
	T19_ = (*headers)->data[T17_].value; (*headers)->data[T17_].value = copyStringRC1(T16_.value);
	if (T19_) nimGCunrefNoCycle(T19_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addDefaultHeaders_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_150)(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* req) {
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23((*req).headers, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_17));
		if (!((T3_ ? T3_->Sup.len : 0) == ((NI) 0))) goto LA4_;
		X5BX5Deq__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_67((&(*req).headers), ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_17), ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_19));
	}
	LA4_: ;
	{
		NimStringDesc* T8_;
		T8_ = (NimStringDesc*)0;
		T8_ = X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23((*req).headers, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_20));
		if (!((T8_ ? T8_->Sup.len : 0) == ((NI) 0))) goto LA9_;
		X5BX5Deq__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_67((&(*req).headers), ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_20), ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_21));
	}
	LA9_: ;
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler_system_2567;
	excHandler_system_2567 = s;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler_system_2567 = (*excHandler_system_2567).prev;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = (Exception*)0;
	result = currException_system_2568;
	return result;
}
static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = (Exception*)0;
	result = currException_system_2568;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_system_2568), (*currException_system_2568).up);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*, fetch_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_154)(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* req) {
	tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ* result;
	tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ* T8_;
	void* volatile hSession;
	void* volatile hConnect;
	void* volatile hRequest;
	TSafePoint TM__qSKfopWphFR2T9ctNAOgqbQ_22;
	tySequence__uFLLGQVsiasALrzzzvqnZw* wideUserAgent;
	NimStringDesc* T13_;
	NI32 ms;
	NU16 volatile port;
	tySequence__uFLLGQVsiasALrzzzvqnZw* wideHostname;
	NI32 volatile openRequestFlags;
	NimStringDesc* volatile objectName;
	tySequence__uFLLGQVsiasALrzzzvqnZw* wideVerb;
	NimStringDesc* T75_;
	tySequence__uFLLGQVsiasALrzzzvqnZw* wideObjectName;
	tySequence__uFLLGQVsiasALrzzzvqnZw* defaultAcceptType;
	tyArray__0A3IEb7UFsBrsbktr2qWew defaultacceptTypes;
	NimStringDesc* volatile requestHeaderBuf;
	tySequence__uFLLGQVsiasALrzzzvqnZw* wideRequestHeaderBuf;
	NI32 volatile statusCode;
	NI32 volatile dwSize;
	NI32 volatile responseHeaderBytes;
	tySequence__uFLLGQVsiasALrzzzvqnZw* volatile responseHeaderBuf;
	NI32 T130_;
	NI32 errorCode;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* responseHeaders;
	NimStringDesc* T147_;
	NI volatile i_4;
	result = (tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*)0;
	{
		NIM_BOOL T3_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T6_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_stdZenumutils_43(TM__qSKfopWphFR2T9ctNAOgqbQ_11, 2, (*(*req).url).scheme);
		if (!!(T3_)) goto LA4_;
		T6_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T6_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T6_).Sup.Sup.Sup.name = "PuppyError";
		T7_ = (NimStringDesc*)0;
		T7_ = rawNewString(((*(*req).url).scheme ? (*(*req).url).scheme->Sup.len : 0) + 28);
appendString(T7_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_14));
appendString(T7_, (*(*req).url).scheme);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.message), T7_);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T6_, "PuppyError", "fetch", "puppy.nim", 85);
	}
	LA4_: ;
	T8_ = (tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*)0;
	T8_ = (tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*) newObj((&NTIresponse__dOa7PNltuukzDKey55t7hw_), sizeof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ));
	result = T8_;
	asgnRef((void**) (&(*result).url), (*req).url);
	addDefaultHeaders_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_150(req);
	{
		if (!((*req).timeout == 0.0f)) goto LA11_;
		(*req).timeout = 60.0f;
	}
	LA11_: ;
	hSession = (void*)0;
	hConnect = (void*)0;
	hRequest = (void*)0;
	pushSafePoint(&TM__qSKfopWphFR2T9ctNAOgqbQ_22);
	TM__qSKfopWphFR2T9ctNAOgqbQ_22.status = setjmp(TM__qSKfopWphFR2T9ctNAOgqbQ_22.context);
	if (TM__qSKfopWphFR2T9ctNAOgqbQ_22.status == 0) {
	T13_ = (NimStringDesc*)0;
	T13_ = X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23((*req).headers, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_17));
	wideUserAgent = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3(T13_);
	if ((NU)(((NI) 0)) >= (NU)(wideUserAgent ? wideUserAgent->Sup.len : 0)){ raiseIndexError2(((NI) 0),(wideUserAgent ? wideUserAgent->Sup.len : 0)-1); }
	hSession = Dl_121634853_((&wideUserAgent->data[((NI) 0)]), ((NI32) 4), ((NU16*) NIM_NIL), ((NU16*) NIM_NIL), ((NI32) 0));
	{
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T18_;
		NimStringDesc* T19_;
		NI32 T20_;
		NimStringDesc* T21_;
		if (!(hSession == NIM_NIL)) goto LA16_;
		T18_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T18_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T18_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T18_).Sup.Sup.Sup.name = "PuppyError";
		T19_ = (NimStringDesc*)0;
		T20_ = (NI32)0;
		T20_ = Dl_121634843_();
		T21_ = (NimStringDesc*)0;
		T21_ = dollar__systemZdollars_3(((NI) (T20_)));
		T19_ = rawNewString((T21_ ? T21_->Sup.len : 0) + 19);
appendString(T19_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_23));
appendString(T19_, T21_);
		asgnRef((void**) (&(*T18_).Sup.Sup.Sup.message), T19_);
		asgnRef((void**) (&(*T18_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T18_, "PuppyError", "fetch", "puppy.nim", 110);
	}
	LA16_: ;
	ms = ((NI32) (((NF32)((*req).timeout) * (NF32)(1000.0f))));
	{
		NI32 T24_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T27_;
		NimStringDesc* T28_;
		NI32 T29_;
		NimStringDesc* T30_;
		T24_ = (NI32)0;
		T24_ = Dl_121634859_(hSession, ms, ms, ms, ms);
		if (!(T24_ == ((NI32) 0))) goto LA25_;
		T27_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T27_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T27_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T27_).Sup.Sup.Sup.name = "PuppyError";
		T28_ = (NimStringDesc*)0;
		T29_ = (NI32)0;
		T29_ = Dl_121634843_();
		T30_ = (NimStringDesc*)0;
		T30_ = dollar__systemZdollars_3(((NI) (T29_)));
		T28_ = rawNewString((T30_ ? T30_->Sup.len : 0) + 26);
appendString(T28_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_24));
appendString(T28_, T30_);
		asgnRef((void**) (&(*T27_).Sup.Sup.Sup.message), T28_);
		asgnRef((void**) (&(*T27_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T27_, "PuppyError", "fetch", "puppy.nim", 116);
	}
	LA25_: ;
	port = (NU16)0;
	{
		if (!(((*(*req).url).port ? (*(*req).url).port->Sup.len : 0) == 0)) goto LA33_;
		if (eqStrings((*(*req).url).scheme, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_12))) goto LA35_;
		if (eqStrings((*(*req).url).scheme, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_13))) goto LA36_;
		goto LA37_;
		LA35_: ;
		{
			port = ((NU16) 80);
		}
		goto LA38_;
		LA36_: ;
		{
			port = ((NU16) 443);
		}
		goto LA38_;
		LA37_: ;
		{
		}
		LA38_: ;
	}
	goto LA31_;
	LA33_: ;
	{
		TSafePoint TM__qSKfopWphFR2T9ctNAOgqbQ_25;
		NI parsedPort;
		pushSafePoint(&TM__qSKfopWphFR2T9ctNAOgqbQ_25);
		TM__qSKfopWphFR2T9ctNAOgqbQ_25.status = setjmp(TM__qSKfopWphFR2T9ctNAOgqbQ_25.context);
		if (TM__qSKfopWphFR2T9ctNAOgqbQ_25.status == 0) {
		parsedPort = nsuParseInt((*(*req).url).port);
		{
			NIM_BOOL T45_;
			tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T49_;
			NimStringDesc* T50_;
			T45_ = (NIM_BOOL)0;
			T45_ = (parsedPort < ((NI) 0));
			if (T45_) goto LA46_;
			T45_ = (((NI) 65535) < parsedPort);
			LA46_: ;
			if (!T45_) goto LA47_;
			T49_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
			T49_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
			(*T49_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
			(*T49_).Sup.Sup.Sup.name = "PuppyError";
			T50_ = (NimStringDesc*)0;
			T50_ = rawNewString(((*(*req).url).port ? (*(*req).url).port->Sup.len : 0) + 14);
appendString(T50_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_26));
appendString(T50_, (*(*req).url).port);
			asgnRef((void**) (&(*T49_).Sup.Sup.Sup.message), T50_);
			asgnRef((void**) (&(*T49_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T49_, "PuppyError", "fetch", "puppy.nim", 133);
		}
		LA47_: ;
		port = ((NU16) (parsedPort));
		popSafePoint();
		}
		else {
			popSafePoint();
			if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_))) {
				tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* e;
				Exception* T53_;
				tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T54_;
				NimStringDesc* T55_;
				TM__qSKfopWphFR2T9ctNAOgqbQ_25.status = 0;
				T53_ = (Exception*)0;
				T53_ = getCurrentException();
				e = ((tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) (T53_));
				T54_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
				T54_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
				(*T54_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
				(*T54_).Sup.Sup.Sup.name = "PuppyError";
				T55_ = (NimStringDesc*)0;
				T55_ = (*T54_).Sup.Sup.Sup.message; (*T54_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_27));
				if (T55_) nimGCunrefNoCycle(T55_);
				asgnRef((void**) (&(*T54_).Sup.Sup.Sup.parent), &e->Sup.Sup);
				raiseExceptionEx((Exception*)T54_, "PuppyError", "fetch", "puppy.nim", 136);
				popCurrentException();
			}
		}
		if (TM__qSKfopWphFR2T9ctNAOgqbQ_25.status != 0) reraiseException();
	}
	LA31_: ;
	wideHostname = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3((*(*req).url).hostname);
	if ((NU)(((NI) 0)) >= (NU)(wideHostname ? wideHostname->Sup.len : 0)){ raiseIndexError2(((NI) 0),(wideHostname ? wideHostname->Sup.len : 0)-1); }
	hConnect = Dl_121634865_(hSession, (&wideHostname->data[((NI) 0)]), port, ((NI32) 0));
	{
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T60_;
		NimStringDesc* T61_;
		NI32 T62_;
		NimStringDesc* T63_;
		if (!(hConnect == NIM_NIL)) goto LA58_;
		T60_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T60_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T60_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T60_).Sup.Sup.Sup.name = "PuppyError";
		T61_ = (NimStringDesc*)0;
		T62_ = (NI32)0;
		T62_ = Dl_121634843_();
		T63_ = (NimStringDesc*)0;
		T63_ = dollar__systemZdollars_3(((NI) (T62_)));
		T61_ = rawNewString((T63_ ? T63_->Sup.len : 0) + 22);
appendString(T61_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_28));
appendString(T61_, T63_);
		asgnRef((void**) (&(*T60_).Sup.Sup.Sup.message), T61_);
		asgnRef((void**) (&(*T60_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T60_, "PuppyError", "fetch", "puppy.nim", 147);
	}
	LA58_: ;
	openRequestFlags = (NI32)0;
	{
		if (!eqStrings((*(*req).url).scheme, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_13))) goto LA66_;
		openRequestFlags = (NI32)(openRequestFlags | ((NI32) 8388608));
	}
	LA66_: ;
	objectName = path_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_542((*req).url);
	{
		NimStringDesc* T70_;
		NimStringDesc* T73_;
		NimStringDesc* T74_;
		T70_ = (NimStringDesc*)0;
		T70_ = search_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_506((*req).url);
		if (!!(((T70_ ? T70_->Sup.len : 0) == 0))) goto LA71_;
		T73_ = (NimStringDesc*)0;
		T74_ = (NimStringDesc*)0;
		T74_ = search_6758Z85sersZxZOnimbleZpkgsZurlly4549O48O48Zurlly_506((*req).url);
		T73_ = rawNewString((T74_ ? T74_->Sup.len : 0) + 1);
appendString(T73_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_29));
appendString(T73_, T74_);
		objectName = resizeString(objectName, (T73_ ? T73_->Sup.len : 0) + 0);
appendString(objectName, T73_);
	}
	LA71_: ;
	T75_ = (NimStringDesc*)0;
	T75_ = nsuToUpperAsciiStr((*req).verb);
	wideVerb = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3(T75_);
	wideObjectName = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3(objectName);
	defaultAcceptType = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_30));
	nimZeroMem((void*)defaultacceptTypes, sizeof(tyArray__0A3IEb7UFsBrsbktr2qWew));
	if ((NU)(((NI) 0)) >= (NU)(defaultAcceptType ? defaultAcceptType->Sup.len : 0)){ raiseIndexError2(((NI) 0),(defaultAcceptType ? defaultAcceptType->Sup.len : 0)-1); }
	defaultacceptTypes[0] = (&defaultAcceptType->data[((NI) 0)]);
	defaultacceptTypes[1] = ((NU16*) NIM_NIL);
	if ((NU)(((NI) 0)) >= (NU)(wideVerb ? wideVerb->Sup.len : 0)){ raiseIndexError2(((NI) 0),(wideVerb ? wideVerb->Sup.len : 0)-1); }
	if ((NU)(((NI) 0)) >= (NU)(wideObjectName ? wideObjectName->Sup.len : 0)){ raiseIndexError2(((NI) 0),(wideObjectName ? wideObjectName->Sup.len : 0)-1); }
	hRequest = Dl_121634870_(hConnect, (&wideVerb->data[((NI) 0)]), (&wideObjectName->data[((NI) 0)]), ((NU16*) NIM_NIL), ((NU16*) NIM_NIL), ((NU16**) (defaultacceptTypes)), openRequestFlags);
	{
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T80_;
		NimStringDesc* T81_;
		NI32 T82_;
		NimStringDesc* T83_;
		if (!(hRequest == NIM_NIL)) goto LA78_;
		T80_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T80_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T80_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T80_).Sup.Sup.Sup.name = "PuppyError";
		T81_ = (NimStringDesc*)0;
		T82_ = (NI32)0;
		T82_ = Dl_121634843_();
		T83_ = (NimStringDesc*)0;
		T83_ = dollar__systemZdollars_3(((NI) (T82_)));
		T81_ = rawNewString((T83_ ? T83_->Sup.len : 0) + 26);
appendString(T81_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_31));
appendString(T81_, T83_);
		asgnRef((void**) (&(*T80_).Sup.Sup.Sup.message), T81_);
		asgnRef((void**) (&(*T80_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T80_, "PuppyError", "fetch", "puppy.nim", 180);
	}
	LA78_: ;
	requestHeaderBuf = (NimStringDesc*)0;
	{
		tyObject_Header__oFhWnxD33zTQi87OVhvcHw* header;
		NI i;
		NI L;
		NI T85_;
		header = (tyObject_Header__oFhWnxD33zTQi87OVhvcHw*)0;
		i = ((NI) 0);
		T85_ = ((*req).headers ? (*req).headers->Sup.len : 0);
		L = T85_;
		{
			while (1) {
				NimStringDesc* T88_;
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_34;
				if (!(i < L)) goto LA87;
				if ((NU)(i) >= (NU)((*req).headers ? (*req).headers->Sup.len : 0)){ raiseIndexError2(i,((*req).headers ? (*req).headers->Sup.len : 0)-1); }
				header = (&(*req).headers->data[i]);
				T88_ = (NimStringDesc*)0;
				T88_ = rawNewString(((*header).key ? (*header).key->Sup.len : 0) + ((*header).value ? (*header).value->Sup.len : 0) + 4);
appendString(T88_, (*header).key);
appendString(T88_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_32));
appendString(T88_, (*header).value);
appendString(T88_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_33));
				requestHeaderBuf = resizeString(requestHeaderBuf, (T88_ ? T88_->Sup.len : 0) + 0);
appendString(requestHeaderBuf, T88_);
				if (nimAddInt(i, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_34)) { raiseOverflow(); };
				i = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_34);
				{
					NI T91_;
					T91_ = ((*req).headers ? (*req).headers->Sup.len : 0);
					if (!!((T91_ == L))) goto LA92_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_7));
				}
				LA92_: ;
			} LA87: ;
		}
	}
	wideRequestHeaderBuf = toUtf16_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_3(requestHeaderBuf);
	{
		NI32 T96_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T99_;
		NimStringDesc* T100_;
		NI32 T101_;
		NimStringDesc* T102_;
		if ((NU)(((NI) 0)) >= (NU)(wideRequestHeaderBuf ? wideRequestHeaderBuf->Sup.len : 0)){ raiseIndexError2(((NI) 0),(wideRequestHeaderBuf ? wideRequestHeaderBuf->Sup.len : 0)-1); }
		T96_ = (NI32)0;
		T96_ = Dl_121634878_(hRequest, (&wideRequestHeaderBuf->data[((NI) 0)]), ((NI32) -1), ((NI32) -1610612736));
		if (!(T96_ == ((NI32) 0))) goto LA97_;
		T99_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T99_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T99_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T99_).Sup.Sup.Sup.name = "PuppyError";
		T100_ = (NimStringDesc*)0;
		T101_ = (NI32)0;
		T101_ = Dl_121634843_();
		T102_ = (NimStringDesc*)0;
		T102_ = dollar__systemZdollars_3(((NI) (T101_)));
		T100_ = rawNewString((T102_ ? T102_->Sup.len : 0) + 32);
appendString(T100_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_35));
appendString(T100_, T102_);
		asgnRef((void**) (&(*T99_).Sup.Sup.Sup.message), T100_);
		asgnRef((void**) (&(*T99_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T99_, "PuppyError", "fetch", "puppy.nim", 196);
	}
	LA97_: ;
	{
		NI32 T105_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T108_;
		NimStringDesc* T109_;
		NI32 T110_;
		NimStringDesc* T111_;
		T105_ = (NI32)0;
		T105_ = Dl_121634883_(hRequest, ((NU16*) NIM_NIL), ((NI32) 0), ((void*) (nimToCStringConv((*req).body))), ((NI32) (((*req).body ? (*req).body->Sup.len : 0))), ((NI32) (((*req).body ? (*req).body->Sup.len : 0))), ((NU32) 0));
		if (!(T105_ == ((NI32) 0))) goto LA106_;
		T108_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T108_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T108_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T108_).Sup.Sup.Sup.name = "PuppyError";
		T109_ = (NimStringDesc*)0;
		T110_ = (NI32)0;
		T110_ = Dl_121634843_();
		T111_ = (NimStringDesc*)0;
		T111_ = dollar__systemZdollars_3(((NI) (T110_)));
		T109_ = rawNewString((T111_ ? T111_->Sup.len : 0) + 26);
appendString(T109_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_36));
appendString(T109_, T111_);
		asgnRef((void**) (&(*T108_).Sup.Sup.Sup.message), T109_);
		asgnRef((void**) (&(*T108_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T108_, "PuppyError", "fetch", "puppy.nim", 209);
	}
	LA106_: ;
	{
		NI32 T114_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T117_;
		NimStringDesc* T118_;
		NI32 T119_;
		NimStringDesc* T120_;
		T114_ = (NI32)0;
		T114_ = Dl_121634891_(hRequest, NIM_NIL);
		if (!(T114_ == ((NI32) 0))) goto LA115_;
		T117_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T117_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T117_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T117_).Sup.Sup.Sup.name = "PuppyError";
		T118_ = (NimStringDesc*)0;
		T119_ = (NI32)0;
		T119_ = Dl_121634843_();
		T120_ = (NimStringDesc*)0;
		T120_ = dollar__systemZdollars_3(((NI) (T119_)));
		T118_ = rawNewString((T120_ ? T120_->Sup.len : 0) + 30);
appendString(T118_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_37));
appendString(T118_, T120_);
		asgnRef((void**) (&(*T117_).Sup.Sup.Sup.message), T118_);
		asgnRef((void**) (&(*T117_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T117_, "PuppyError", "fetch", "puppy.nim", 214);
	}
	LA115_: ;
	statusCode = (NI32)0;
	dwSize = ((NI32) 4);
	{
		NI32 T123_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T126_;
		NimStringDesc* T127_;
		NI32 T128_;
		NimStringDesc* T129_;
		T123_ = (NI32)0;
		T123_ = Dl_121634894_(hRequest, ((NI32) 536870931), ((NU16*) NIM_NIL), ((void*) ((&statusCode))), (&dwSize), ((NI32*) NIM_NIL));
		if (!(T123_ == ((NI32) 0))) goto LA124_;
		T126_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T126_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T126_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T126_).Sup.Sup.Sup.name = "PuppyError";
		T127_ = (NimStringDesc*)0;
		T128_ = (NI32)0;
		T128_ = Dl_121634843_();
		T129_ = (NimStringDesc*)0;
		T129_ = dollar__systemZdollars_3(((NI) (T128_)));
		T127_ = rawNewString((T129_ ? T129_->Sup.len : 0) + 27);
appendString(T127_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_38));
appendString(T127_, T129_);
		asgnRef((void**) (&(*T126_).Sup.Sup.Sup.message), T127_);
		asgnRef((void**) (&(*T126_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T126_, "PuppyError", "fetch", "puppy.nim", 229);
	}
	LA124_: ;
	(*result).code = ((NI) (statusCode));
	responseHeaderBytes = (NI32)0;
	responseHeaderBuf = (tySequence__uFLLGQVsiasALrzzzvqnZw*)0;
	T130_ = (NI32)0;
	T130_ = Dl_121634894_(hRequest, ((NI32) 22), ((NU16*) NIM_NIL), NIM_NIL, (&responseHeaderBytes), ((NI32*) NIM_NIL));
	(void)(T130_);
	errorCode = Dl_121634843_();
	{
		NI TM__qSKfopWphFR2T9ctNAOgqbQ_39;
		NI TM__qSKfopWphFR2T9ctNAOgqbQ_40;
		if (!(errorCode == ((NI32) 122))) goto LA133_;
		if (((NI) 2) == 0){ raiseDivByZero(); }
		if (nimDivInt(((NI) (responseHeaderBytes)), ((NI) 2), &TM__qSKfopWphFR2T9ctNAOgqbQ_39)) { raiseOverflow(); };
		if (nimAddInt((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_39), ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_40)) { raiseOverflow(); };
		if (((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_40)) < ((NI) 0) || ((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_40)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_40), ((NI) 0), ((NI) 2147483647)); }
		responseHeaderBuf = (tySequence__uFLLGQVsiasALrzzzvqnZw*) setLengthSeqV2(&(responseHeaderBuf)->Sup, (&NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_), ((NI) ((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_40))));
	}
	goto LA131_;
	LA133_: ;
	{
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T136_;
		NimStringDesc* T137_;
		NimStringDesc* T138_;
		T136_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T136_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T136_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T136_).Sup.Sup.Sup.name = "PuppyError";
		T137_ = (NimStringDesc*)0;
		T138_ = (NimStringDesc*)0;
		T138_ = dollar__systemZdollars_3(((NI) (errorCode)));
		T137_ = rawNewString((T138_ ? T138_->Sup.len : 0) + 22);
appendString(T137_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_41));
appendString(T137_, T138_);
		asgnRef((void**) (&(*T136_).Sup.Sup.Sup.message), T137_);
		asgnRef((void**) (&(*T136_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T136_, "PuppyError", "fetch", "puppy.nim", 253);
	}
	LA131_: ;
	{
		NI32 T141_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T144_;
		NimStringDesc* T145_;
		NimStringDesc* T146_;
		if ((NU)(((NI) 0)) >= (NU)(responseHeaderBuf ? responseHeaderBuf->Sup.len : 0)){ raiseIndexError2(((NI) 0),(responseHeaderBuf ? responseHeaderBuf->Sup.len : 0)-1); }
		T141_ = (NI32)0;
		T141_ = Dl_121634894_(hRequest, ((NI32) 22), ((NU16*) NIM_NIL), ((void*) ((&responseHeaderBuf->data[((NI) 0)]))), (&responseHeaderBytes), ((NI32*) NIM_NIL));
		if (!(T141_ == ((NI32) 0))) goto LA142_;
		T144_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T144_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T144_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T144_).Sup.Sup.Sup.name = "PuppyError";
		T145_ = (NimStringDesc*)0;
		T146_ = (NimStringDesc*)0;
		T146_ = dollar__systemZdollars_3(((NI) (errorCode)));
		T145_ = rawNewString((T146_ ? T146_->Sup.len : 0) + 22);
appendString(T145_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_41));
appendString(T145_, T146_);
		asgnRef((void**) (&(*T144_).Sup.Sup.Sup.message), T145_);
		asgnRef((void**) (&(*T144_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T144_, "PuppyError", "fetch", "puppy.nim", 266);
	}
	LA142_: ;
	T147_ = (NimStringDesc*)0;
	T147_ = toUtf8_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48ZpuppyZwinutils_27(responseHeaderBuf);
	responseHeaders = nsuSplitString(T147_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_33), ((NI) -1));
	{
		NI T150_;
		tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T153_;
		NimStringDesc* T154_;
		T150_ = (responseHeaders ? responseHeaders->Sup.len : 0);
		if (!(T150_ == ((NI) 0))) goto LA151_;
		T153_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
		T153_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
		(*T153_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
		(*T153_).Sup.Sup.Sup.name = "PuppyError";
		T154_ = (NimStringDesc*)0;
		T154_ = (*T153_).Sup.Sup.Sup.message; (*T153_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_42));
		if (T154_) nimGCunrefNoCycle(T154_);
		asgnRef((void**) (&(*T153_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T153_, "PuppyError", "fetch", "puppy.nim", 276);
	}
	LA151_: ;
	{
		NI i_2;
		NimStringDesc* line;
		NI i_3;
		NI L_2;
		NI T156_;
		i_2 = (NI)0;
		line = (NimStringDesc*)0;
		i_3 = ((NI) 0);
		T156_ = (responseHeaders ? responseHeaders->Sup.len : 0);
		L_2 = T156_;
		{
			while (1) {
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_45;
				if (!(i_3 < L_2)) goto LA158;
				i_2 = i_3;
				if ((NU)(i_3) >= (NU)(responseHeaders ? responseHeaders->Sup.len : 0)){ raiseIndexError2(i_3,(responseHeaders ? responseHeaders->Sup.len : 0)-1); }
				line = responseHeaders->data[i_3];
				{
					{
						if (!(i_2 == ((NI) 0))) goto LA162_;
						goto LA159;
					}
					LA162_: ;
					{
						tySequence__sM4lkSb7zS6F7OVMvW9cffQ* parts;
						if (!!(((line ? line->Sup.len : 0) == 0))) goto LA166_;
						parts = nsuSplitString(line, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_43), ((NI) 1));
						{
							NI T170_;
							NimStringDesc* T173_;
							NimStringDesc* T174_;
							T170_ = (parts ? parts->Sup.len : 0);
							if (!(T170_ == ((NI) 2))) goto LA171_;
							if ((NU)(((NI) 0)) >= (NU)(parts ? parts->Sup.len : 0)){ raiseIndexError2(((NI) 0),(parts ? parts->Sup.len : 0)-1); }
							T173_ = (NimStringDesc*)0;
							T173_ = nsuStrip(parts->data[((NI) 0)], NIM_TRUE, NIM_TRUE, TM__qSKfopWphFR2T9ctNAOgqbQ_44);
							if ((NU)(((NI) 1)) >= (NU)(parts ? parts->Sup.len : 0)){ raiseIndexError2(((NI) 1),(parts ? parts->Sup.len : 0)-1); }
							T174_ = (NimStringDesc*)0;
							T174_ = nsuStrip(parts->data[((NI) 1)], NIM_TRUE, NIM_TRUE, TM__qSKfopWphFR2T9ctNAOgqbQ_44);
							X5BX5Deq__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_67((&(*result).headers), T173_, T174_);
						}
						LA171_: ;
					}
					LA166_: ;
				} LA159: ;
				if (nimAddInt(i_3, ((NI) 1), &TM__qSKfopWphFR2T9ctNAOgqbQ_45)) { raiseOverflow(); };
				i_3 = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_45);
				{
					NI T177_;
					T177_ = (responseHeaders ? responseHeaders->Sup.len : 0);
					if (!!((T177_ == L_2))) goto LA178_;
					failedAssertImpl_systemZassertions_56(((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_46));
				}
				LA178_: ;
			} LA158: ;
		}
	}
	i_4 = (NI)0;
	asgnRef((void**) (&(*result).body), setLengthStr((*result).body, ((NI) 8192)));
	{
		while (1) {
			NI32 volatile bytesRead;
			NI TM__qSKfopWphFR2T9ctNAOgqbQ_49;
			bytesRead = (NI32)0;
			{
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_47;
				NI32 T184_;
				tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T187_;
				NimStringDesc* T188_;
				NI32 T189_;
				NimStringDesc* T190_;
				if ((NU)(i_4) >= (NU)((*result).body ? (*result).body->Sup.len : 0)){ raiseIndexError2(i_4,((*result).body ? (*result).body->Sup.len : 0)-1); }
				if (nimSubInt(((*result).body ? (*result).body->Sup.len : 0), i_4, &TM__qSKfopWphFR2T9ctNAOgqbQ_47)) { raiseOverflow(); };
				T184_ = (NI32)0;
				T184_ = Dl_121634901_(hRequest, ((void*) ((&(*result).body->data[i_4]))), ((NI32) ((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_47))), (&bytesRead));
				if (!(T184_ == ((NI32) 0))) goto LA185_;
				T187_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
				T187_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
				(*T187_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
				(*T187_).Sup.Sup.Sup.name = "PuppyError";
				T188_ = (NimStringDesc*)0;
				T189_ = (NI32)0;
				T189_ = Dl_121634843_();
				T190_ = (NimStringDesc*)0;
				T190_ = dollar__systemZdollars_3(((NI) (T189_)));
				T188_ = rawNewString((T190_ ? T190_->Sup.len : 0) + 23);
appendString(T188_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_48));
appendString(T188_, T190_);
				asgnRef((void**) (&(*T187_).Sup.Sup.Sup.message), T188_);
				asgnRef((void**) (&(*T187_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
				raiseExceptionEx((Exception*)T187_, "PuppyError", "fetch", "puppy.nim", 297);
			}
			LA185_: ;
			if (nimAddInt(i_4, ((NI) (bytesRead)), &TM__qSKfopWphFR2T9ctNAOgqbQ_49)) { raiseOverflow(); };
			i_4 = (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_49);
			{
				if (!(bytesRead == ((NI32) 0))) goto LA193_;
				goto LA180;
			}
			LA193_: ;
			{
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_50;
				NI TM__qSKfopWphFR2T9ctNAOgqbQ_51;
				if (!(i_4 == ((*result).body ? (*result).body->Sup.len : 0))) goto LA197_;
				if (nimMulInt(i_4, ((NI) 2), &TM__qSKfopWphFR2T9ctNAOgqbQ_50)) { raiseOverflow(); };
				if (nimAddInt(i_4, ((NI) 104857600), &TM__qSKfopWphFR2T9ctNAOgqbQ_51)) { raiseOverflow(); };
				if (((((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) <= (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51)) ? (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) : (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51))) < ((NI) 0) || ((((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) <= (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51)) ? (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) : (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51))) > ((NI) 2147483647)){ raiseRangeErrorI((((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) <= (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51)) ? (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) : (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51)), ((NI) 0), ((NI) 2147483647)); }
				asgnRef((void**) (&(*result).body), setLengthStr((*result).body, ((NI) ((((NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) <= (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51)) ? (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_50) : (NI)(TM__qSKfopWphFR2T9ctNAOgqbQ_51))))));
			}
			LA197_: ;
		}
	} LA180: ;
	if ((i_4) < ((NI) 0) || (i_4) > ((NI) 2147483647)){ raiseRangeErrorI(i_4, ((NI) 0), ((NI) 2147483647)); }
	asgnRef((void**) (&(*result).body), setLengthStr((*result).body, ((NI) (i_4))));
	{
		NimStringDesc* T201_;
		NimStringDesc* T202_;
		T201_ = (NimStringDesc*)0;
		T201_ = X5BX5D__6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_23((*result).headers, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_52));
		T202_ = (NimStringDesc*)0;
		T202_ = nsuToLowerAsciiStr(T201_);
		if (!eqStrings(T202_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_21))) goto LA203_;
		asgnRef((void**) (&(*result).body), uncompress_6758Z85sersZxZOnimbleZpkgsZzippy4548O55O51Zzippy_262((*result).body, ((tyEnum_CompressedDataFormat__ClEuT0guPTPUtivU3r4e9aA) 2)));
	}
	LA203_: ;
	popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		NI32 T207_;
		NI32 T208_;
		NI32 T209_;
		T207_ = (NI32)0;
		T207_ = Dl_121634906_(hRequest);
		(void)(T207_);
		T208_ = (NI32)0;
		T208_ = Dl_121634906_(hConnect);
		(void)(T208_);
		T209_ = (NI32)0;
		T209_ = Dl_121634906_(hSession);
		(void)(T209_);
		if (TM__qSKfopWphFR2T9ctNAOgqbQ_22.status != 0) nimLeaveFinally();
	}
	if (TM__qSKfopWphFR2T9ctNAOgqbQ_22.status != 0) reraiseException();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, fetch_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_337)(NimStringDesc* url, tySequence__wfzhy8RTNYkMytxQXIPT1A* headers) {
	NimStringDesc* result;
	tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA* req;
	tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ* res;
	tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA* T5_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
{	result = (NimStringDesc*)0;
	req = newRequest_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_305(url, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_8), headers, 60.0f);
	res = fetch_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_154(req);
	{
		if (!((*res).code == ((NI) 200))) goto LA3_;
		result = copyString((*res).body);
		goto BeforeRet_;
	}
	LA3_: ;
	T5_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*)0;
	T5_ = (tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA*) newObj((&NTIrefpuppyerror__P9czev7PkJcfQ9beI09c30g2Q_), sizeof(tyObject_PuppyError__aGZ9b9cwY1HiCWzYqDORSpRA));
	(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIpuppyerror__aGZ9b9cwY1HiCWzYqDORSpRA_);
	(*T5_).Sup.Sup.Sup.name = "PuppyError";
	T6_ = (NimStringDesc*)0;
	T7_ = (NimStringDesc*)0;
	T7_ = dollar__systemZdollars_3((*res).code);
	T6_ = rawNewString((T7_ ? T7_->Sup.len : 0) + ((*res).body ? (*res).body->Sup.len : 0) + 24);
appendString(T6_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_53));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM__qSKfopWphFR2T9ctNAOgqbQ_54));
appendString(T6_, (*res).body);
	asgnRef((void**) (&(*T5_).Sup.Sup.Sup.message), T6_);
	asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T5_, "PuppyError", "fetch", "puppy.nim", 474);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__wfzhy8RTNYkMytxQXIPT1A*, newSeq_6758Z85sersZxZOnimbleZpkgsZpuppy4549O52O48Zpuppy_308)(NI len) {
	tySequence__wfzhy8RTNYkMytxQXIPT1A* result;
	result = (tySequence__wfzhy8RTNYkMytxQXIPT1A*)0;
	result = (tySequence__wfzhy8RTNYkMytxQXIPT1A*) newSeq((&NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_), len);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, puppy_puppyDatInit000)(void) {
static TNimNode* TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[5];
static TNimNode* TM__qSKfopWphFR2T9ctNAOgqbQ_3_2[2];
static TNimNode* TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[4];
static TNimNode TM__qSKfopWphFR2T9ctNAOgqbQ_0[14];
NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_.size = sizeof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA);
NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_.align = NIM_ALIGNOF(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA);
NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_.kind = 18;
NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_.base = 0;
TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[0] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[1];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[1].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[1].offset = offsetof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA, url);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[1].typ = (&NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[1].name = "url";
TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[1] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[2];
NTIheader__oFhWnxD33zTQi87OVhvcHw_.size = sizeof(tyObject_Header__oFhWnxD33zTQi87OVhvcHw);
NTIheader__oFhWnxD33zTQi87OVhvcHw_.align = NIM_ALIGNOF(tyObject_Header__oFhWnxD33zTQi87OVhvcHw);
NTIheader__oFhWnxD33zTQi87OVhvcHw_.kind = 18;
NTIheader__oFhWnxD33zTQi87OVhvcHw_.base = 0;
TM__qSKfopWphFR2T9ctNAOgqbQ_3_2[0] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[4];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[4].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[4].offset = offsetof(tyObject_Header__oFhWnxD33zTQi87OVhvcHw, key);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[4].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[4].name = "key";
TM__qSKfopWphFR2T9ctNAOgqbQ_3_2[1] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[5];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[5].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[5].offset = offsetof(tyObject_Header__oFhWnxD33zTQi87OVhvcHw, value);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[5].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[5].name = "value";
TM__qSKfopWphFR2T9ctNAOgqbQ_0[3].len = 2; TM__qSKfopWphFR2T9ctNAOgqbQ_0[3].kind = 2; TM__qSKfopWphFR2T9ctNAOgqbQ_0[3].sons = &TM__qSKfopWphFR2T9ctNAOgqbQ_3_2[0];
NTIheader__oFhWnxD33zTQi87OVhvcHw_.node = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[3];
NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_.size = sizeof(tySequence__wfzhy8RTNYkMytxQXIPT1A*);
NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_.align = NIM_ALIGNOF(tySequence__wfzhy8RTNYkMytxQXIPT1A*);
NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_.kind = 24;
NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_.base = (&NTIheader__oFhWnxD33zTQi87OVhvcHw_);
NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_.marker = Marker_tySequence__wfzhy8RTNYkMytxQXIPT1A;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[2].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[2].offset = offsetof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA, headers);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[2].typ = (&NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[2].name = "headers";
TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[2] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[6];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[6].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[6].offset = offsetof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA, timeout);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[6].typ = (&NTIfloat__C875xFvYpI7aGybrDGHIaQ_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[6].name = "timeout";
TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[3] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[7];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[7].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[7].offset = offsetof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA, verb);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[7].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[7].name = "verb";
TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[4] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[8];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[8].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[8].offset = offsetof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA, body);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[8].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[8].name = "body";
TM__qSKfopWphFR2T9ctNAOgqbQ_0[0].len = 5; TM__qSKfopWphFR2T9ctNAOgqbQ_0[0].kind = 2; TM__qSKfopWphFR2T9ctNAOgqbQ_0[0].sons = &TM__qSKfopWphFR2T9ctNAOgqbQ_2_5[0];
NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_.node = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[0];
NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_.size = sizeof(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*);
NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_.align = NIM_ALIGNOF(tyObject_RequestcolonObjectType___jKviEQuwNioN3KW4HvGhEA*);
NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_.kind = 22;
NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_.base = (&NTIrequest58objecttype__jKviEQuwNioN3KW4HvGhEA_);
NTIrequest__PnYa0s029a36UKFZ9c9bwgo8g_.marker = Marker_tyRef__PnYa0s029a36UKFZ9c9bwgo8g;
NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_.size = sizeof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ);
NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_.align = NIM_ALIGNOF(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ);
NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_.kind = 18;
NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_.base = 0;
TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[0] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[10];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[10].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[10].offset = offsetof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ, url);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[10].typ = (&NTIurl__c0EiIY9aN7Vc09cjtTz7R9alA_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[10].name = "url";
TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[1] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[11];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[11].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[11].offset = offsetof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ, headers);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[11].typ = (&NTIseqLheaderT__wfzhy8RTNYkMytxQXIPT1A_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[11].name = "headers";
TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[2] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[12];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[12].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[12].offset = offsetof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ, code);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[12].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[12].name = "code";
TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[3] = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[13];
TM__qSKfopWphFR2T9ctNAOgqbQ_0[13].kind = 1;
TM__qSKfopWphFR2T9ctNAOgqbQ_0[13].offset = offsetof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ, body);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[13].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__qSKfopWphFR2T9ctNAOgqbQ_0[13].name = "body";
TM__qSKfopWphFR2T9ctNAOgqbQ_0[9].len = 4; TM__qSKfopWphFR2T9ctNAOgqbQ_0[9].kind = 2; TM__qSKfopWphFR2T9ctNAOgqbQ_0[9].sons = &TM__qSKfopWphFR2T9ctNAOgqbQ_15_4[0];
NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_.node = &TM__qSKfopWphFR2T9ctNAOgqbQ_0[9];
NTIresponse__dOa7PNltuukzDKey55t7hw_.size = sizeof(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*);
NTIresponse__dOa7PNltuukzDKey55t7hw_.align = NIM_ALIGNOF(tyObject_ResponsecolonObjectType___pgYE9bW0R8e29bSHdEChi9beQ*);
NTIresponse__dOa7PNltuukzDKey55t7hw_.kind = 22;
NTIresponse__dOa7PNltuukzDKey55t7hw_.base = (&NTIresponse58objecttype__pgYE9bW0R8e29bSHdEChi9beQ_);
NTIresponse__dOa7PNltuukzDKey55t7hw_.marker = Marker_tyRef__dOa7PNltuukzDKey55t7hw;
}

